%------------------------------------------------------------------------------
% File     : SWC530_1 : TPTP v9.2.1. Bugfixed v9.1.0.
% Domain   : Software Creation
% Problem  : Atelier-B Proof Obligation: PO 1 4 Group s127 Tag s135
% Version  : Especial.
% English  :

% Refs     : [Deh22] Deharbe (2022), Proof Obligations from the B Formal Me
%          : [Deh24] Deharbe (2024), Email to Geoff Sutcliffe
% Source   : [Deh24]
% Names    : 0012-00132-1-4.tptp [Deh24]

% Status   : Theorem
% Rating   : ? v9.1.0
% Syntax   : Number of formulae    :  328 (  91 unt; 145 typ;   0 def)
%            Number of atoms       :  637 (  88 equ)
%            Maximal formula atoms :   20 (   3 avg)
%            Number of connectives :  462 (   4   ~;   3   |; 231   &)
%                                         (  94 <=>; 130  =>;   0  <=;   0 <~>)
%            Maximal formula depth :   19 (   4 avg)
%            Maximal term depth    :    5 (   1 avg)
%            Number of FOOLs       :   16 (   0 fml;  16 var)
%            Number arithmetic     :  677 (  57 atm;  56 fun;  61 num; 503 var)
%            Number of types       :    8 (   6 usr;   1 ari)
%            Number of type conns  :   25 (  11   >;  14   *;   0   +;   0  <<)
%            Number of predicates  :   13 (   6 usr;   2 prp; 0-5 aty)
%            Number of functors    :  149 ( 133 usr; 139 con; 0-2 aty)
%            Number of variables   :  564 ( 434   !; 130   ?; 564   :)
% SPC      : TX0_THM_EQU_ARI

% Comments : Autogenerated by PPTRANS-TPTP - github.com/CLEARSY/pptranspog
% Bugfixes : v9.1.0 - Added missing types, and maybe more.
%------------------------------------------------------------------------------
tff(set_0_type,type,
    set_0: $tType ).

tff(mem0_type,type,
    mem0: ( $int * set_0 ) > $o ).

tff(min_int_type,type,
    min_int: $int ).

tff(max_int_type,type,
    max_int: $int ).

tff(min_int_axiom,axiom,
    min_int = $uminus(2147483648) ).

tff(max_int_axiom,axiom,
    max_int = 2147483647 ).

%----Global declarations
tff(g_s0_0_type,type,
    g_s0_0: set_0 ).

tff(g_s1_1_type,type,
    g_s1_1: $int ).

tff(g_s2_2_type,type,
    g_s2_2: $int ).

tff(g_s4_3_type,type,
    g_s4_3: set_0 ).

tff(g_s3_4_type,type,
    g_s3_4: $int ).

tff(g_s6_5_type,type,
    g_s6_5: set_0 ).

tff(g_s5_6_type,type,
    g_s5_6: $int ).

tff(g_s8_7_type,type,
    g_s8_7: set_0 ).

tff(g_s7_8_type,type,
    g_s7_8: $int ).

tff(g_s9_9_type,type,
    g_s9_9: $int ).

tff(g_s10_10_type,type,
    g_s10_10: $int ).

tff(g_s11_11_type,type,
    g_s11_11: set_0 ).

tff(set_2_type,type,
    set_2: $tType ).

tff(set_2_empty,type,
    set_2_empty: set_2 ).

tff(set_2_insert,type,
    set_2_insert: set_2 > set_2 ).

tff(g_s12_12_type,type,
    g_s12_12: set_2 ).

tff(mem2_type,type,
    mem2: ( $o * $int * set_2 ) > $o ).

tff(g_s13_13_type,type,
    g_s13_13: $int ).

tff(g_s14_14_type,type,
    g_s14_14: $int ).

tff(g_s15_15_type,type,
    g_s15_15: $int ).

tff(g_s16_16_type,type,
    g_s16_16: $int ).

tff(g_s17_17_type,type,
    g_s17_17: $int ).

tff(g_s18_18_type,type,
    g_s18_18: $int ).

tff(g_s19_19_type,type,
    g_s19_19: $int ).

tff(g_s20_20_type,type,
    g_s20_20: $int ).

tff(g_s21_21_type,type,
    g_s21_21: $int ).

tff(g_s22_22_type,type,
    g_s22_22: $int ).

tff(g_s23_23_type,type,
    g_s23_23: $int ).

tff(g_s24_24_type,type,
    g_s24_24: $int ).

tff(g_s25_25_type,type,
    g_s25_25: $int ).

tff(g_s26_26_type,type,
    g_s26_26: $int ).

tff(g_s27_27_type,type,
    g_s27_27: $int ).

tff(g_s28_28_type,type,
    g_s28_28: $int ).

tff(g_s29_29_type,type,
    g_s29_29: $int ).

tff(g_s30_30_type,type,
    g_s30_30: $int ).

tff(g_s31_31_type,type,
    g_s31_31: $int ).

tff(g_s32_32_type,type,
    g_s32_32: $int ).

tff(g_s33_33_type,type,
    g_s33_33: $int ).

tff(g_s34_34_type,type,
    g_s34_34: $int ).

tff(set_3_type,type,
    set_3: $tType ).

tff(set_3_empty,type,
    set_3_empty: set_3 ).

tff(set_3_insert,type,
    set_3_insert: set_3 > set_3 ).

tff(g_s36_35_type,type,
    g_s36_35: set_3 ).

tff(mem3_type,type,
    mem3: ( $int * $int * $int * set_3 ) > $o ).

tff(g_s37_36_type,type,
    g_s37_36: $int ).

tff(g_s38_37_type,type,
    g_s38_37: $int ).

tff(g_s39_38_type,type,
    g_s39_38: $int ).

tff(g_s40_39_type,type,
    g_s40_39: $int ).

tff(g_s41_40_type,type,
    g_s41_40: $int ).

tff(g_s42_41_type,type,
    g_s42_41: $int ).

tff(g_s43_42_type,type,
    g_s43_42: $int ).

tff(g_s44_43_type,type,
    g_s44_43: $int ).

tff(g_s45_44_type,type,
    g_s45_44: $int ).

tff(g_s46_45_type,type,
    g_s46_45: $int ).

tff(g_s47_46_type,type,
    g_s47_46: $int ).

tff(g_s48_47_type,type,
    g_s48_47: $int ).

tff(g_s49_48_type,type,
    g_s49_48: $int ).

tff(g_s50_49_type,type,
    g_s50_49: $int ).

tff(g_s51_50_type,type,
    g_s51_50: $int ).

tff(g_s52_51_type,type,
    g_s52_51: $int ).

tff(g_s53_52_type,type,
    g_s53_52: $int ).

tff(g_s54_53_type,type,
    g_s54_53: $int ).

tff(g_s55_54_type,type,
    g_s55_54: $int ).

tff(g_s56_55_type,type,
    g_s56_55: $int ).

tff(g_s57_56_type,type,
    g_s57_56: $int ).

tff(g_s58_57_type,type,
    g_s58_57: $int ).

tff(g_s59_58_type,type,
    g_s59_58: $int ).

tff(g_s60_59_type,type,
    g_s60_59: $int ).

tff(g_s61_60_type,type,
    g_s61_60: $int ).

tff(g_s62_61_type,type,
    g_s62_61: $int ).

tff(g_s63_62_type,type,
    g_s63_62: $int ).

tff(g_s64_63_type,type,
    g_s64_63: $int ).

tff(g_s65_64_type,type,
    g_s65_64: $int ).

tff(g_s66_65_type,type,
    g_s66_65: $int ).

tff(g_s67_66_type,type,
    g_s67_66: $int ).

tff(g_s68_67_type,type,
    g_s68_67: $int ).

tff(g_s69_68_type,type,
    g_s69_68: $int ).

tff(g_s70_69_type,type,
    g_s70_69: $int ).

tff(g_s71_70_type,type,
    g_s71_70: $int ).

tff(g_s72_71_type,type,
    g_s72_71: $int ).

tff(g_s73_72_type,type,
    g_s73_72: $int ).

tff(g_s74_73_type,type,
    g_s74_73: $int ).

tff(g_s75_74_type,type,
    g_s75_74: $int ).

tff(g_s76_75_type,type,
    g_s76_75: $int ).

tff(g_s77_76_type,type,
    g_s77_76: $int ).

tff(g_s78_77_type,type,
    g_s78_77: $int ).

tff(g_s79_78_type,type,
    g_s79_78: $int ).

tff(set_4_type,type,
    set_4: $tType ).

tff(set_4_empty,type,
    set_4_empty: set_4 ).

tff(set_4_insert,type,
    set_4_insert: set_4 > set_4 ).

tff(mem4_type,type,
    mem4: ( $int * $int * set_4 ) > $o ).

tff(g_s80_79_type,type,
    g_s80_79: set_4 ).

tff(g_s81_80_type,type,
    g_s81_80: set_4 ).

tff(g_s82_81_type,type,
    g_s82_81: set_3 ).

tff(g_s83_82_type,type,
    g_s83_82: set_4 ).

tff(g_s84_83_type,type,
    g_s84_83: set_3 ).

tff(g_s85_84_type,type,
    g_s85_84: set_3 ).

tff(g_s86_85_type,type,
    g_s86_85: set_4 ).

tff(g_s87_86_type,type,
    g_s87_86: set_3 ).

tff(g_s88_87_type,type,
    g_s88_87: set_3 ).

tff(g_s89_88_type,type,
    g_s89_88: set_3 ).

tff(g_s90_89_type,type,
    g_s90_89: set_3 ).

tff(g_s91_90_type,type,
    g_s91_90: set_3 ).

tff(g_s92_91_type,type,
    g_s92_91: set_3 ).

tff(g_s93_92_type,type,
    g_s93_92: set_3 ).

tff(g_s94_93_type,type,
    g_s94_93: set_3 ).

tff(g_s95_94_type,type,
    g_s95_94: set_3 ).

tff(g_s96_95_type,type,
    g_s96_95: set_3 ).

tff(g_s97_96_type,type,
    g_s97_96: set_3 ).

tff(g_s98_97_type,type,
    g_s98_97: set_3 ).

tff(g_s103_98_type,type,
    g_s103_98: set_3 ).

tff(g_s104_99_type,type,
    g_s104_99: set_3 ).

tff(g_s105_100_type,type,
    g_s105_100: set_3 ).

tff(set_5_type,type,
    set_5: $tType ).

tff(set_5_empty,type,
    set_5_empty: set_5 ).

tff(set_5_insert,type,
    set_5_insert: set_5 > set_5 ).

tff(mem5_type,type,
    mem5: ( $int * set_4 * $int * $int * set_5 ) > $o ).

tff(g_s106_101_type,type,
    g_s106_101: set_5 ).

tff(g_s107_102_type,type,
    g_s107_102: $int ).

tff(g_s109_1_103_type,type,
    g_s109_1_103: set_4 ).

tff(g_s108_105_type,type,
    g_s108_105: set_4 ).

tff(g_s109_106_type,type,
    g_s109_106: set_4 ).

tff(g_s112_107_type,type,
    g_s112_107: set_4 ).

tff(g_s113_108_type,type,
    g_s113_108: set_4 ).

tff(set_6_type,type,
    set_6: $tType ).

tff(set_6_empty,type,
    set_6_empty: set_6 ).

tff(set_6_insert,type,
    set_6_insert: set_6 > set_6 ).

tff(g_s114_109_type,type,
    g_s114_109: set_6 ).

tff(mem6_type,type,
    mem6: ( $int * set_4 * set_6 ) > $o ).

tff(g_s119_110_type,type,
    g_s119_110: set_0 ).

tff(g_s120_111_type,type,
    g_s120_111: set_0 ).

tff(g_s122_1_112_type,type,
    g_s122_1_112: set_4 ).

tff(g_s123_1_113_type,type,
    g_s123_1_113: set_4 ).

tff(g_s124_1_114_type,type,
    g_s124_1_114: set_4 ).

tff(g_s128_115_type,type,
    g_s128_115: $int ).

tff(g_s129_116_type,type,
    g_s129_116: $int ).

tff(g_s130_117_type,type,
    g_s130_117: $int ).

tff(g_s131_118_type,type,
    g_s131_118: $int ).

tff(g_s132_119_type,type,
    g_s132_119: $int ).

tff(g_s133_120_type,type,
    g_s133_120: $int ).

tff(g_s134_121_type,type,
    g_s134_121: $int ).

%----Defines
tff('Define:abs:0',axiom,
    ? [X_435: set_4] :
      ( ! [X_436: $int,X_437: $int] :
          ( mem4(X_437,X_436,X_435)
        <=> mem4(X_437,X_436,g_s108_105) )
      & ! [X_438: $int,X_439: $int,X_440: $int] :
          ( ( mem4(X_438,X_439,X_435)
            & mem4(X_438,X_440,X_435) )
         => ( X_439 = X_440 ) )
      & ! [X_441: $int] :
          ( mem0(X_441,g_s0_0)
        <=> ? [X_442: $int] : mem4(X_441,X_442,X_435) )
      & ! [X_443: $int] :
          ( ? [X_444: $int] : mem4(X_444,X_443,X_435)
         => $true ) ) ).

tff('Define:abs:1',axiom,
    ? [X_445: set_4] :
      ( ! [X_446: $int,X_447: $int] :
          ( mem4(X_447,X_446,X_445)
        <=> mem4(X_447,X_446,g_s109_106) )
      & ! [X_448: $int,X_449: $int,X_450: $int] :
          ( ( mem4(X_448,X_449,X_445)
            & mem4(X_448,X_450,X_445) )
         => ( X_449 = X_450 ) )
      & ! [X_451: $int] :
          ( mem0(X_451,g_s0_0)
        <=> ? [X_452: $int] : mem4(X_451,X_452,X_445) )
      & ! [X_453: $int] :
          ( ? [X_454: $int] : mem4(X_454,X_453,X_445)
         => $true ) ) ).

tff('Define:abs:10',axiom,
    ! [L_s117: $int] :
      ( mem0(L_s117,g_s0_0)
     => ! [X_498: $int] :
          ( ? [X_499: $int] :
              ( ! [X_500: $int,X_501: $int] :
                  ( ( mem4(L_s117,X_500,g_s112_107)
                    & mem4(L_s117,X_501,g_s113_108) )
                 => ( $greatereq(X_499,X_500)
                    & $lesseq(X_499,X_501) ) )
              & ! [X_502: set_4] :
                  ( mem6(L_s117,X_502,g_s114_109)
                 => mem4(X_499,X_498,X_502) ) )
        <=> ! [X_503: set_4,X_504: $int] :
              ( ( mem6(L_s117,X_503,g_s114_109)
                & mem4(L_s117,X_504,g_s113_108) )
             => mem4(X_504,X_498,X_503) ) ) ) ).

tff('Define:abs:11',axiom,
    ! [L_s118: $int] :
      ( mem0(L_s118,g_s0_0)
     => ! [X_505: $int,X_506: $int] :
          ( ( mem4(L_s118,X_505,g_s112_107)
            & mem4(L_s118,X_506,g_s113_108) )
         => $lesseq(X_505,X_506) ) ) ).

tff('Define:abs:12',axiom,
    ? [X_507: set_4] :
      ( ! [X_508: $int,X_509: $int] :
          ( mem4(X_509,X_508,X_507)
        <=> mem4(X_509,X_508,g_s113_108) )
      & ! [X_510: $int,X_511: $int,X_512: $int] :
          ( ( mem4(X_510,X_511,X_507)
            & mem4(X_510,X_512,X_507) )
         => ( X_511 = X_512 ) )
      & ! [X_513: $int] :
          ( mem0(X_513,g_s0_0)
        <=> ? [X_514: $int] : mem4(X_513,X_514,X_507) )
      & ! [X_515: $int] :
          ( ? [X_516: $int] : mem4(X_516,X_515,X_507)
         => $greatereq(X_515,0) ) ) ).

tff('Define:abs:13',axiom,
    ? [X_517: set_6] :
      ( ! [X_518: set_4,X_519: $int] :
          ( mem6(X_519,X_518,X_517)
        <=> mem6(X_519,X_518,g_s114_109) )
      & ! [X_520: $int,X_521: set_4,X_522: set_4] :
          ( ( mem6(X_520,X_521,X_517)
            & mem6(X_520,X_522,X_517) )
         => ! [X_523: $int,X_524: $int] :
              ( mem4(X_524,X_523,X_521)
            <=> mem4(X_524,X_523,X_522) ) )
      & ! [X_525: $int] :
          ( mem0(X_525,g_s0_0)
        <=> ? [X_526: set_4] : mem6(X_525,X_526,X_517) )
      & ! [X_527: set_4] :
          ( ? [X_528: $int] : mem6(X_528,X_527,X_517)
         => ( ! [X_529: $int,X_530: $int] :
                ( mem4(X_530,X_529,X_527)
               => ( $greatereq(X_530,0)
                  & $true ) )
            & ! [X_531: $int,X_532: $int,X_533: $int] :
                ( ( mem4(X_531,X_532,X_527)
                  & mem4(X_531,X_533,X_527) )
               => ( X_532 = X_533 ) ) ) ) ) ).

tff('Define:abs:14',axiom,
    ! [X_534: $int] :
      ( mem0(X_534,g_s119_110)
     => mem0(X_534,g_s0_0) ) ).

tff('Define:abs:15',axiom,
    ! [X_535: $int] :
      ( mem0(X_535,g_s120_111)
     => mem0(X_535,g_s0_0) ) ).

tff('Define:abs:16',axiom,
    ! [L_s121: $int] :
      ( mem0(L_s121,g_s0_0)
     => ! [X_536: $int] :
          ( ? [X_537: $int] :
            ! [X_538: set_4] :
              ( mem6(L_s121,X_538,g_s114_109)
             => mem4(X_536,X_537,X_538) )
        <=> ! [X_539: $int] :
              ( mem4(L_s121,X_539,g_s113_108)
             => ( $greatereq(X_536,0)
                & $lesseq(X_536,X_539) ) ) ) ) ).

tff('Define:abs:17',axiom,
    ! [X_540: $int] :
      ( mem0(X_540,g_s119_110)
     => mem0(X_540,g_s0_0) ) ).

tff('Define:abs:18',axiom,
    ! [X_541: $int] :
      ( mem0(X_541,g_s120_111)
     => mem0(X_541,g_s0_0) ) ).

tff('Define:abs:2',axiom,
    ! [L_s110: $int] :
      ( mem0(L_s110,g_s0_0)
     => ! [X_455: $int] :
          ( mem4(L_s110,X_455,g_s109_106)
         => $lesseq(X_455,g_s38_37) ) ) ).

tff('Define:abs:3',axiom,
    ! [L_s111: $int] :
      ( mem0(L_s111,g_s0_0)
     => ! [X_456: $int] :
          ( ! [X_457: $int,X_458: $int] :
              ( ( mem4(L_s111,X_457,g_s113_108)
                & mem4(L_s111,X_458,g_s109_106) )
             => ( X_456 = $difference($sum(X_457,X_458),g_s38_37) ) )
         => mem4(L_s111,X_456,g_s112_107) ) ) ).

tff('Define:abs:4',axiom,
    ? [X_459: set_4] :
      ( ! [X_460: $int,X_461: $int] :
          ( mem4(X_461,X_460,X_459)
        <=> mem4(X_461,X_460,g_s108_105) )
      & ! [X_462: $int,X_463: $int,X_464: $int] :
          ( ( mem4(X_462,X_463,X_459)
            & mem4(X_462,X_464,X_459) )
         => ( X_463 = X_464 ) )
      & ! [X_465: $int] :
          ( mem0(X_465,g_s0_0)
        <=> ? [X_466: $int] : mem4(X_465,X_466,X_459) )
      & ! [X_467: $int] :
          ( ? [X_468: $int] : mem4(X_468,X_467,X_459)
         => $true ) ) ).

tff('Define:abs:5',axiom,
    ? [X_469: set_4] :
      ( ! [X_470: $int,X_471: $int] :
          ( mem4(X_471,X_470,X_469)
        <=> mem4(X_471,X_470,g_s112_107) )
      & ! [X_472: $int,X_473: $int,X_474: $int] :
          ( ( mem4(X_472,X_473,X_469)
            & mem4(X_472,X_474,X_469) )
         => ( X_473 = X_474 ) )
      & ! [X_475: $int] :
          ( mem0(X_475,g_s0_0)
        <=> ? [X_476: $int] : mem4(X_475,X_476,X_469) )
      & ! [X_477: $int] :
          ( ? [X_478: $int] : mem4(X_478,X_477,X_469)
         => $greatereq(X_477,0) ) ) ).

tff('Define:abs:6',axiom,
    ! [L_s110: $int] :
      ( mem0(L_s110,g_s0_0)
     => ! [X_479: $int] :
          ( ! [X_480: set_4,X_481: $int] :
              ( ( mem6(L_s110,X_480,g_s114_109)
                & mem4(L_s110,X_481,g_s113_108) )
             => mem4(X_481,X_479,X_480) )
         => mem4(L_s110,X_479,g_s108_105) ) ) ).

tff('Define:abs:7',axiom,
    ! [L_s115: $int] :
      ( ( mem0(L_s115,g_s0_0)
        & ! [X_482: $int] :
            ( mem4(L_s115,X_482,g_s112_107)
           => $lesseq(1,X_482) ) )
     => ? [X_483: $int] :
        ! [X_484: set_4,X_485: $int] :
          ( ( mem6(L_s115,X_484,g_s114_109)
            & mem4(L_s115,X_485,g_s112_107) )
         => mem4(X_485,X_483,X_484) ) ) ).

tff('Define:abs:8',axiom,
    ! [L_s116: $int] :
      ( ( mem0(L_s116,g_s0_0)
        & ! [X_486: $int] :
            ( mem4(L_s116,X_486,g_s112_107)
           => $lesseq(1,X_486) ) )
     => ? [X_487: $int] :
        ! [X_488: set_4,X_489: $int] :
          ( ( mem6(L_s116,X_488,g_s114_109)
            & ! [X_490: $int] :
                ( mem4(L_s116,X_490,g_s112_107)
               => ( X_489 = $difference(X_490,1) ) ) )
         => mem4(X_489,X_487,X_488) ) ) ).

tff('Define:abs:9',axiom,
    ! [L_s111: $int] :
      ( ( mem0(L_s111,g_s0_0)
        & ! [X_491: $int] :
            ( mem4(L_s111,X_491,g_s112_107)
           => $lesseq(1,X_491) ) )
     => ~ ! [X_492: set_4,X_493: $int,X_494: $int] :
            ( ( mem6(L_s111,X_492,g_s114_109)
              & mem4(L_s111,X_493,g_s112_107)
              & ! [X_495: set_4,X_496: $int] :
                  ( ( mem6(L_s111,X_495,g_s114_109)
                    & ! [X_497: $int] :
                        ( mem4(L_s111,X_497,g_s112_107)
                       => ( X_496 = $difference(X_497,1) ) ) )
                 => mem4(X_496,X_494,X_495) ) )
           => mem4(X_493,X_494,X_492) ) ) ).

tff('Define:ctx:0',axiom,
    ( ! [X_5: $int] :
        ( mem0(X_5,g_s0_0)
      <=> ( ( X_5 = g_s1_1 )
          | ( X_5 = g_s2_2 ) ) )
    & ( g_s1_1 != g_s2_2 ) ) ).

tff('Define:ctx:1',axiom,
    mem0(g_s3_4,g_s4_3) ).

tff('Define:ctx:10',axiom,
    ( $greatereq(g_s10_10,0)
    & $lesseq(g_s10_10,g_s7_8) ) ).

tff('Define:ctx:100',axiom,
    mem0(g_s78_77,g_s4_3) ).

tff('Define:ctx:101',axiom,
    mem0(g_s79_78,g_s4_3) ).

tff('Define:ctx:102',axiom,
    ? [X_13: set_4] :
      ( ! [X_14: $int,X_15: $int] :
          ( mem4(X_15,X_14,X_13)
        <=> mem4(X_15,X_14,g_s80_79) )
      & ! [X_16: $int,X_17: $int,X_18: $int] :
          ( ( mem4(X_16,X_17,X_13)
            & mem4(X_16,X_18,X_13) )
         => ( X_17 = X_18 ) )
      & ! [X_19: $int] :
          ( ( $greatereq(X_19,0)
            & $lesseq(X_19,1023) )
        <=> ? [X_20: $int] : mem4(X_19,X_20,X_13) )
      & ! [X_21: $int] :
          ( ? [X_22: $int] : mem4(X_22,X_21,X_13)
         => mem0(X_21,g_s4_3) ) ) ).

tff('Define:ctx:103',axiom,
    ? [X_23: set_4] :
      ( ! [X_24: $int,X_25: $int] :
          ( mem4(X_25,X_24,X_23)
        <=> mem4(X_25,X_24,g_s81_80) )
      & ! [X_26: $int,X_27: $int,X_28: $int] :
          ( ( mem4(X_26,X_27,X_23)
            & mem4(X_26,X_28,X_23) )
         => ( X_27 = X_28 ) )
      & ! [X_29: $int] :
          ( mem0(X_29,g_s4_3)
        <=> ? [X_30: $int] : mem4(X_29,X_30,X_23) )
      & ! [X_31: $int] :
          ( ? [X_32: $int] : mem4(X_32,X_31,X_23)
         => mem0(X_31,g_s4_3) ) ) ).

tff('Define:ctx:104',axiom,
    ? [X_33: set_3] :
      ( ! [X_34: $int,X_35: $int,X_36: $int] :
          ( mem3(X_36,X_35,X_34,X_33)
        <=> mem3(X_36,X_35,X_34,g_s36_35) )
      & ! [X_37: $int,X_38: $int,X_39: $int,X_40: $int] :
          ( ( mem3(X_38,X_37,X_39,X_33)
            & mem3(X_38,X_37,X_40,X_33) )
         => ( X_39 = X_40 ) )
      & ! [X_41: $int,X_42: $int] :
          ( ( mem0(X_42,g_s4_3)
            & mem0(X_41,g_s4_3) )
        <=> ? [X_43: $int] : mem3(X_42,X_41,X_43,X_33) )
      & ! [X_44: $int] :
          ( ? [X_45: $int,X_46: $int] : mem3(X_46,X_45,X_44,X_33)
         => mem0(X_44,g_s4_3) ) ) ).

tff('Define:ctx:105',axiom,
    ? [X_47: set_3] :
      ( ! [X_48: $int,X_49: $int,X_50: $int] :
          ( mem3(X_50,X_49,X_48,X_47)
        <=> mem3(X_50,X_49,X_48,g_s82_81) )
      & ! [X_51: $int,X_52: $int,X_53: $int,X_54: $int] :
          ( ( mem3(X_52,X_51,X_53,X_47)
            & mem3(X_52,X_51,X_54,X_47) )
         => ( X_53 = X_54 ) )
      & ! [X_55: $int,X_56: $int] :
          ( ( mem0(X_56,g_s4_3)
            & mem0(X_55,g_s4_3) )
        <=> ? [X_57: $int] : mem3(X_56,X_55,X_57,X_47) )
      & ! [X_58: $int] :
          ( ? [X_59: $int,X_60: $int] : mem3(X_60,X_59,X_58,X_47)
         => mem0(X_58,g_s4_3) ) ) ).

tff('Define:ctx:106',axiom,
    ? [X_61: set_4] :
      ( ! [X_62: $int,X_63: $int] :
          ( mem4(X_63,X_62,X_61)
        <=> mem4(X_63,X_62,g_s83_82) )
      & ! [X_64: $int,X_65: $int,X_66: $int] :
          ( ( mem4(X_64,X_65,X_61)
            & mem4(X_64,X_66,X_61) )
         => ( X_65 = X_66 ) )
      & ! [X_67: $int] :
          ( mem0(X_67,g_s6_5)
        <=> ? [X_68: $int] : mem4(X_67,X_68,X_61) )
      & ! [X_69: $int] :
          ( ? [X_70: $int] : mem4(X_70,X_69,X_61)
         => mem0(X_69,g_s6_5) ) ) ).

tff('Define:ctx:107',axiom,
    ? [X_71: set_3] :
      ( ! [X_72: $int,X_73: $int,X_74: $int] :
          ( mem3(X_74,X_73,X_72,X_71)
        <=> mem3(X_74,X_73,X_72,g_s84_83) )
      & ! [X_75: $int,X_76: $int,X_77: $int,X_78: $int] :
          ( ( mem3(X_76,X_75,X_77,X_71)
            & mem3(X_76,X_75,X_78,X_71) )
         => ( X_77 = X_78 ) )
      & ! [X_79: $int,X_80: $int] :
          ( ( mem0(X_80,g_s6_5)
            & mem0(X_79,g_s6_5) )
        <=> ? [X_81: $int] : mem3(X_80,X_79,X_81,X_71) )
      & ! [X_82: $int] :
          ( ? [X_83: $int,X_84: $int] : mem3(X_84,X_83,X_82,X_71)
         => mem0(X_82,g_s6_5) ) ) ).

tff('Define:ctx:108',axiom,
    ? [X_85: set_3] :
      ( ! [X_86: $int,X_87: $int,X_88: $int] :
          ( mem3(X_88,X_87,X_86,X_85)
        <=> mem3(X_88,X_87,X_86,g_s85_84) )
      & ! [X_89: $int,X_90: $int,X_91: $int,X_92: $int] :
          ( ( mem3(X_90,X_89,X_91,X_85)
            & mem3(X_90,X_89,X_92,X_85) )
         => ( X_91 = X_92 ) )
      & ! [X_93: $int,X_94: $int] :
          ( ( mem0(X_94,g_s6_5)
            & mem0(X_93,g_s6_5) )
        <=> ? [X_95: $int] : mem3(X_94,X_93,X_95,X_85) )
      & ! [X_96: $int] :
          ( ? [X_97: $int,X_98: $int] : mem3(X_98,X_97,X_96,X_85)
         => mem0(X_96,g_s6_5) ) ) ).

tff('Define:ctx:109',axiom,
    ? [X_99: set_4] :
      ( ! [X_100: $int,X_101: $int] :
          ( mem4(X_101,X_100,X_99)
        <=> mem4(X_101,X_100,g_s86_85) )
      & ! [X_102: $int,X_103: $int,X_104: $int] :
          ( ( mem4(X_102,X_103,X_99)
            & mem4(X_102,X_104,X_99) )
         => ( X_103 = X_104 ) )
      & ! [X_105: $int] :
          ( mem0(X_105,g_s8_7)
        <=> ? [X_106: $int] : mem4(X_105,X_106,X_99) )
      & ! [X_107: $int] :
          ( ? [X_108: $int] : mem4(X_108,X_107,X_99)
         => mem0(X_107,g_s8_7) ) ) ).

tff('Define:ctx:11',axiom,
    g_s9_9 != g_s10_10 ).

tff('Define:ctx:110',axiom,
    ? [X_109: set_3] :
      ( ! [X_110: $int,X_111: $int,X_112: $int] :
          ( mem3(X_112,X_111,X_110,X_109)
        <=> mem3(X_112,X_111,X_110,g_s87_86) )
      & ! [X_113: $int,X_114: $int,X_115: $int,X_116: $int] :
          ( ( mem3(X_114,X_113,X_115,X_109)
            & mem3(X_114,X_113,X_116,X_109) )
         => ( X_115 = X_116 ) )
      & ! [X_117: $int,X_118: $int] :
          ( ( mem0(X_118,g_s8_7)
            & mem0(X_117,g_s8_7) )
        <=> ? [X_119: $int] : mem3(X_118,X_117,X_119,X_109) )
      & ! [X_120: $int] :
          ( ? [X_121: $int,X_122: $int] : mem3(X_122,X_121,X_120,X_109)
         => mem0(X_120,g_s8_7) ) ) ).

tff('Define:ctx:111',axiom,
    ? [X_123: set_3] :
      ( ! [X_124: $int,X_125: $int,X_126: $int] :
          ( mem3(X_126,X_125,X_124,X_123)
        <=> mem3(X_126,X_125,X_124,g_s88_87) )
      & ! [X_127: $int,X_128: $int,X_129: $int,X_130: $int] :
          ( ( mem3(X_128,X_127,X_129,X_123)
            & mem3(X_128,X_127,X_130,X_123) )
         => ( X_129 = X_130 ) )
      & ! [X_131: $int,X_132: $int] :
          ( ( mem0(X_132,g_s8_7)
            & mem0(X_131,g_s8_7) )
        <=> ? [X_133: $int] : mem3(X_132,X_131,X_133,X_123) )
      & ! [X_134: $int] :
          ( ? [X_135: $int,X_136: $int] : mem3(X_136,X_135,X_134,X_123)
         => mem0(X_134,g_s8_7) ) ) ).

tff('Define:ctx:112',axiom,
    ? [X_137: set_3] :
      ( ! [X_138: $int,X_139: $int,X_140: $int] :
          ( mem3(X_140,X_139,X_138,X_137)
        <=> mem3(X_140,X_139,X_138,g_s89_88) )
      & ! [X_141: $int,X_142: $int,X_143: $int,X_144: $int] :
          ( ( mem3(X_142,X_141,X_143,X_137)
            & mem3(X_142,X_141,X_144,X_137) )
         => ( X_143 = X_144 ) )
      & ! [X_145: $int,X_146: $int] :
          ( ( mem0(X_146,g_s8_7)
            & mem0(X_145,g_s8_7) )
        <=> ? [X_147: $int] : mem3(X_146,X_145,X_147,X_137) )
      & ! [X_148: $int] :
          ( ? [X_149: $int,X_150: $int] : mem3(X_150,X_149,X_148,X_137)
         => mem0(X_148,g_s8_7) ) ) ).

tff('Define:ctx:113',axiom,
    ? [X_151: set_3] :
      ( ! [X_152: $int,X_153: $int,X_154: $int] :
          ( mem3(X_154,X_153,X_152,X_151)
        <=> mem3(X_154,X_153,X_152,g_s90_89) )
      & ! [X_155: $int,X_156: $int,X_157: $int,X_158: $int] :
          ( ( mem3(X_156,X_155,X_157,X_151)
            & mem3(X_156,X_155,X_158,X_151) )
         => ( X_157 = X_158 ) )
      & ! [X_159: $int,X_160: $int] :
          ( ( mem0(X_160,g_s4_3)
            & mem0(X_159,g_s4_3) )
        <=> ? [X_161: $int] : mem3(X_160,X_159,X_161,X_151) )
      & ! [X_162: $int] :
          ( ? [X_163: $int,X_164: $int] : mem3(X_164,X_163,X_162,X_151)
         => mem0(X_162,g_s4_3) ) ) ).

tff('Define:ctx:114',axiom,
    ? [X_165: set_3] :
      ( ! [X_166: $int,X_167: $int,X_168: $int] :
          ( mem3(X_168,X_167,X_166,X_165)
        <=> mem3(X_168,X_167,X_166,g_s91_90) )
      & ! [X_169: $int,X_170: $int,X_171: $int,X_172: $int] :
          ( ( mem3(X_170,X_169,X_171,X_165)
            & mem3(X_170,X_169,X_172,X_165) )
         => ( X_171 = X_172 ) )
      & ! [X_173: $int,X_174: $int] :
          ( ( mem0(X_174,g_s4_3)
            & mem0(X_173,g_s4_3) )
        <=> ? [X_175: $int] : mem3(X_174,X_173,X_175,X_165) )
      & ! [X_176: $int] :
          ( ? [X_177: $int,X_178: $int] : mem3(X_178,X_177,X_176,X_165)
         => mem0(X_176,g_s4_3) ) ) ).

tff('Define:ctx:115',axiom,
    ? [X_179: set_3] :
      ( ! [X_180: $int,X_181: $int,X_182: $int] :
          ( mem3(X_182,X_181,X_180,X_179)
        <=> mem3(X_182,X_181,X_180,g_s92_91) )
      & ! [X_183: $int,X_184: $int,X_185: $int,X_186: $int] :
          ( ( mem3(X_184,X_183,X_185,X_179)
            & mem3(X_184,X_183,X_186,X_179) )
         => ( X_185 = X_186 ) )
      & ! [X_187: $int,X_188: $int] :
          ( ( mem0(X_188,g_s4_3)
            & mem0(X_187,g_s4_3) )
        <=> ? [X_189: $int] : mem3(X_188,X_187,X_189,X_179) )
      & ! [X_190: $int] :
          ( ? [X_191: $int,X_192: $int] : mem3(X_192,X_191,X_190,X_179)
         => mem0(X_190,g_s4_3) ) ) ).

tff('Define:ctx:116',axiom,
    ? [X_193: set_3] :
      ( ! [X_194: $int,X_195: $int,X_196: $int] :
          ( mem3(X_196,X_195,X_194,X_193)
        <=> mem3(X_196,X_195,X_194,g_s93_92) )
      & ! [X_197: $int,X_198: $int,X_199: $int,X_200: $int] :
          ( ( mem3(X_198,X_197,X_199,X_193)
            & mem3(X_198,X_197,X_200,X_193) )
         => ( X_199 = X_200 ) )
      & ! [X_201: $int,X_202: $int] :
          ( ( mem0(X_202,g_s6_5)
            & mem0(X_201,g_s6_5) )
        <=> ? [X_203: $int] : mem3(X_202,X_201,X_203,X_193) )
      & ! [X_204: $int] :
          ( ? [X_205: $int,X_206: $int] : mem3(X_206,X_205,X_204,X_193)
         => mem0(X_204,g_s6_5) ) ) ).

tff('Define:ctx:117',axiom,
    ? [X_207: set_3] :
      ( ! [X_208: $int,X_209: $int,X_210: $int] :
          ( mem3(X_210,X_209,X_208,X_207)
        <=> mem3(X_210,X_209,X_208,g_s94_93) )
      & ! [X_211: $int,X_212: $int,X_213: $int,X_214: $int] :
          ( ( mem3(X_212,X_211,X_213,X_207)
            & mem3(X_212,X_211,X_214,X_207) )
         => ( X_213 = X_214 ) )
      & ! [X_215: $int,X_216: $int] :
          ( ( mem0(X_216,g_s6_5)
            & mem0(X_215,g_s6_5) )
        <=> ? [X_217: $int] : mem3(X_216,X_215,X_217,X_207) )
      & ! [X_218: $int] :
          ( ? [X_219: $int,X_220: $int] : mem3(X_220,X_219,X_218,X_207)
         => mem0(X_218,g_s6_5) ) ) ).

tff('Define:ctx:118',axiom,
    ? [X_221: set_3] :
      ( ! [X_222: $int,X_223: $int,X_224: $int] :
          ( mem3(X_224,X_223,X_222,X_221)
        <=> mem3(X_224,X_223,X_222,g_s95_94) )
      & ! [X_225: $int,X_226: $int,X_227: $int,X_228: $int] :
          ( ( mem3(X_226,X_225,X_227,X_221)
            & mem3(X_226,X_225,X_228,X_221) )
         => ( X_227 = X_228 ) )
      & ! [X_229: $int,X_230: $int] :
          ( ( mem0(X_230,g_s6_5)
            & mem0(X_229,g_s6_5) )
        <=> ? [X_231: $int] : mem3(X_230,X_229,X_231,X_221) )
      & ! [X_232: $int] :
          ( ? [X_233: $int,X_234: $int] : mem3(X_234,X_233,X_232,X_221)
         => mem0(X_232,g_s6_5) ) ) ).

tff('Define:ctx:119',axiom,
    ? [X_235: set_3] :
      ( ! [X_236: $int,X_237: $int,X_238: $int] :
          ( mem3(X_238,X_237,X_236,X_235)
        <=> mem3(X_238,X_237,X_236,g_s96_95) )
      & ! [X_239: $int,X_240: $int,X_241: $int,X_242: $int] :
          ( ( mem3(X_240,X_239,X_241,X_235)
            & mem3(X_240,X_239,X_242,X_235) )
         => ( X_241 = X_242 ) )
      & ! [X_243: $int,X_244: $int] :
          ( ( mem0(X_244,g_s8_7)
            & mem0(X_243,g_s8_7) )
        <=> ? [X_245: $int] : mem3(X_244,X_243,X_245,X_235) )
      & ! [X_246: $int] :
          ( ? [X_247: $int,X_248: $int] : mem3(X_248,X_247,X_246,X_235)
         => mem0(X_246,g_s8_7) ) ) ).

tff('Define:ctx:12',axiom,
    ! [X_6: $int] :
      ( mem0(X_6,g_s11_11)
    <=> ( ( X_6 = g_s9_9 )
        | ( X_6 = g_s10_10 ) ) ) ).

tff('Define:ctx:120',axiom,
    ? [X_249: set_3] :
      ( ! [X_250: $int,X_251: $int,X_252: $int] :
          ( mem3(X_252,X_251,X_250,X_249)
        <=> mem3(X_252,X_251,X_250,g_s97_96) )
      & ! [X_253: $int,X_254: $int,X_255: $int,X_256: $int] :
          ( ( mem3(X_254,X_253,X_255,X_249)
            & mem3(X_254,X_253,X_256,X_249) )
         => ( X_255 = X_256 ) )
      & ! [X_257: $int,X_258: $int] :
          ( ( mem0(X_258,g_s8_7)
            & mem0(X_257,g_s8_7) )
        <=> ? [X_259: $int] : mem3(X_258,X_257,X_259,X_249) )
      & ! [X_260: $int] :
          ( ? [X_261: $int,X_262: $int] : mem3(X_262,X_261,X_260,X_249)
         => mem0(X_260,g_s8_7) ) ) ).

tff('Define:ctx:121',axiom,
    ? [X_263: set_3] :
      ( ! [X_264: $int,X_265: $int,X_266: $int] :
          ( mem3(X_266,X_265,X_264,X_263)
        <=> mem3(X_266,X_265,X_264,g_s98_97) )
      & ! [X_267: $int,X_268: $int,X_269: $int,X_270: $int] :
          ( ( mem3(X_268,X_267,X_269,X_263)
            & mem3(X_268,X_267,X_270,X_263) )
         => ( X_269 = X_270 ) )
      & ! [X_271: $int,X_272: $int] :
          ( ( mem0(X_272,g_s8_7)
            & mem0(X_271,g_s8_7) )
        <=> ? [X_273: $int] : mem3(X_272,X_271,X_273,X_263) )
      & ! [X_274: $int] :
          ( ? [X_275: $int,X_276: $int] : mem3(X_276,X_275,X_274,X_263)
         => mem0(X_274,g_s8_7) ) ) ).

tff('Define:ctx:122',axiom,
    ! [X_277: $int,X_278: $int,X_279: $int] :
      ( mem3(X_279,X_278,X_277,g_s90_89)
    <=> ( mem0(X_279,g_s4_3)
        & mem0(X_278,g_s4_3)
        & ( X_277 = $remainder_f($sum(X_279,X_278),$sum(g_s3_4,1)) ) ) ) ).

tff('Define:ctx:123',axiom,
    ! [X_280: $int,X_281: $int,X_282: $int] :
      ( mem3(X_282,X_281,X_280,g_s91_90)
    <=> ( mem0(X_282,g_s4_3)
        & mem0(X_281,g_s4_3)
        & ( X_280 = $remainder_f($sum($sum($difference(X_282,X_281),g_s3_4),1),$sum(g_s3_4,1)) ) ) ) ).

tff('Define:ctx:124',axiom,
    ! [X_283: $int,X_284: $int,X_285: $int] :
      ( mem3(X_285,X_284,X_283,g_s92_91)
    <=> ( mem0(X_285,g_s4_3)
        & mem0(X_284,g_s4_3)
        & ( X_283 = $remainder_f($product(X_285,X_284),$sum(g_s3_4,1)) ) ) ) ).

tff('Define:ctx:125',axiom,
    ! [X_286: $int,X_287: $int,X_288: $int] :
      ( mem3(X_288,X_287,X_286,g_s93_92)
    <=> ( mem0(X_288,g_s6_5)
        & mem0(X_287,g_s6_5)
        & ( X_286 = $remainder_f($sum(X_288,X_287),$sum(g_s5_6,1)) ) ) ) ).

tff('Define:ctx:126',axiom,
    ! [X_289: $int,X_290: $int,X_291: $int] :
      ( mem3(X_291,X_290,X_289,g_s94_93)
    <=> ( mem0(X_291,g_s6_5)
        & mem0(X_290,g_s6_5)
        & ( X_289 = $remainder_f($sum($sum($difference(X_291,X_290),g_s5_6),1),$sum(g_s5_6,1)) ) ) ) ).

tff('Define:ctx:127',axiom,
    ! [X_292: $int,X_293: $int,X_294: $int] :
      ( mem3(X_294,X_293,X_292,g_s95_94)
    <=> ( mem0(X_294,g_s6_5)
        & mem0(X_293,g_s6_5)
        & ( X_292 = $remainder_f($product(X_294,X_293),$sum(g_s5_6,1)) ) ) ) ).

tff('Define:ctx:128',axiom,
    ! [X_295: $int,X_296: $int,X_297: $int] :
      ( mem3(X_297,X_296,X_295,g_s96_95)
    <=> ( mem0(X_297,g_s8_7)
        & mem0(X_296,g_s8_7)
        & ( X_295 = $remainder_f($sum(X_297,X_296),$sum(g_s7_8,1)) ) ) ) ).

tff('Define:ctx:129',axiom,
    ! [X_298: $int,X_299: $int,X_300: $int] :
      ( mem3(X_300,X_299,X_298,g_s97_96)
    <=> ( mem0(X_300,g_s8_7)
        & mem0(X_299,g_s8_7)
        & ( X_298 = $remainder_f($sum($sum($difference(X_300,X_299),g_s7_8),1),$sum(g_s7_8,1)) ) ) ) ).

tff('Define:ctx:13',axiom,
    ! [X_7: $int,X_8: $o] :
      ( mem2((X_8),X_7,g_s12_12)
    <=> ( ( ( (X_8)
          <=> $true )
          & ( X_7 = g_s9_9 ) )
        | ( ( (X_8)
          <=> $false )
          & ( X_7 = g_s10_10 ) ) ) ) ).

tff('Define:ctx:130',axiom,
    ! [X_301: $int,X_302: $int,X_303: $int] :
      ( mem3(X_303,X_302,X_301,g_s98_97)
    <=> ( mem0(X_303,g_s8_7)
        & mem0(X_302,g_s8_7)
        & ( X_301 = $remainder_f($product(X_303,X_302),$sum(g_s7_8,1)) ) ) ) ).

tff('Define:ctx:131',axiom,
    ! [L_s35: $int] :
      ( mem0(L_s35,g_s4_3)
     => ! [X_304: $int] :
          ( ! [X_305: $int] :
              ( ( X_305 = 1023 )
             => mem3(L_s35,X_305,X_304,g_s36_35) )
         => $lesseq(X_304,1023) ) ) ).

tff('Define:ctx:132',axiom,
    ? [X_306: set_3] :
      ( ! [X_307: $int,X_308: $int,X_309: $int] :
          ( mem3(X_309,X_308,X_307,X_306)
        <=> mem3(X_309,X_308,X_307,g_s103_98) )
      & ! [X_310: $int,X_311: $int,X_312: $int,X_313: $int] :
          ( ( mem3(X_311,X_310,X_312,X_306)
            & mem3(X_311,X_310,X_313,X_306) )
         => ( X_312 = X_313 ) )
      & ! [X_314: $int,X_315: $int] :
          ( ( mem0(X_315,g_s4_3)
            & mem0(X_314,g_s4_3) )
        <=> ? [X_316: $int] : mem3(X_315,X_314,X_316,X_306) )
      & ! [X_317: $int] :
          ( ? [X_318: $int,X_319: $int] : mem3(X_319,X_318,X_317,X_306)
         => mem0(X_317,g_s4_3) ) ) ).

tff('Define:ctx:133',axiom,
    ! [X_320: $int,X_321: $int,X_322: $int] :
      ( ( ( X_320 = 0 )
        & ( X_321 = 0 )
        & ( X_322 = 0 ) )
     => mem3(X_320,X_321,X_322,g_s103_98) ) ).

tff('Define:ctx:134',axiom,
    ? [X_323: set_3] :
      ( ! [X_324: $int,X_325: $int,X_326: $int] :
          ( mem3(X_326,X_325,X_324,X_323)
        <=> mem3(X_326,X_325,X_324,g_s104_99) )
      & ! [X_327: $int,X_328: $int,X_329: $int,X_330: $int] :
          ( ( mem3(X_328,X_327,X_329,X_323)
            & mem3(X_328,X_327,X_330,X_323) )
         => ( X_329 = X_330 ) )
      & ! [X_331: $int,X_332: $int] :
          ( ( mem0(X_332,g_s6_5)
            & mem0(X_331,g_s6_5) )
        <=> ? [X_333: $int] : mem3(X_332,X_331,X_333,X_323) )
      & ! [X_334: $int] :
          ( ? [X_335: $int,X_336: $int] : mem3(X_336,X_335,X_334,X_323)
         => mem0(X_334,g_s6_5) ) ) ).

tff('Define:ctx:135',axiom,
    ? [X_337: set_3] :
      ( ! [X_338: $int,X_339: $int,X_340: $int] :
          ( mem3(X_340,X_339,X_338,X_337)
        <=> mem3(X_340,X_339,X_338,g_s105_100) )
      & ! [X_341: $int,X_342: $int,X_343: $int,X_344: $int] :
          ( ( mem3(X_342,X_341,X_343,X_337)
            & mem3(X_342,X_341,X_344,X_337) )
         => ( X_343 = X_344 ) )
      & ! [X_345: $int,X_346: $int] :
          ( ( mem0(X_346,g_s4_3)
            & mem0(X_345,g_s4_3) )
        <=> ? [X_347: $int] : mem3(X_346,X_345,X_347,X_337) )
      & ! [X_348: $int] :
          ( ? [X_349: $int,X_350: $int] : mem3(X_350,X_349,X_348,X_337)
         => mem0(X_348,g_s4_3) ) ) ).

tff('Define:ctx:136',axiom,
    ? [X_351: set_5] :
      ( ! [X_352: $int,X_353: $int,X_354: set_4,X_355: $int] :
          ( mem5(X_355,X_354,X_353,X_352,X_351)
        <=> mem5(X_355,X_354,X_353,X_352,g_s106_101) )
      & ! [X_356: $int,X_357: set_4,X_358: $int,X_359: $int,X_360: $int] :
          ( ( mem5(X_358,X_357,X_356,X_359,X_351)
            & mem5(X_358,X_357,X_356,X_360,X_351) )
         => ( X_359 = X_360 ) )
      & ! [X_361: $int,X_362: set_4,X_363: $int] :
          ( ( mem0(X_363,g_s4_3)
            & ? [X_364: set_4] :
                ( ! [X_365: $int,X_366: $int] :
                    ( mem4(X_366,X_365,X_364)
                  <=> mem4(X_366,X_365,X_362) )
                & ! [X_367: $int,X_368: $int,X_369: $int] :
                    ( ( mem4(X_367,X_368,X_364)
                      & mem4(X_367,X_369,X_364) )
                   => ( X_368 = X_369 ) )
                & ! [X_370: $int] :
                    ( ( $greatereq(X_370,0)
                      & $lesseq(X_370,g_s107_102) )
                  <=> ? [X_371: $int] : mem4(X_370,X_371,X_364) )
                & ! [X_372: $int] :
                    ( ? [X_373: $int] : mem4(X_373,X_372,X_364)
                   => mem0(X_372,g_s4_3) ) )
            & mem0(X_361,g_s4_3) )
        <=> ? [X_374: $int] : mem5(X_363,X_362,X_361,X_374,X_351) )
      & ! [X_375: $int] :
          ( ? [X_376: $int,X_377: set_4,X_378: $int] : mem5(X_378,X_377,X_376,X_375,X_351)
         => mem0(X_375,g_s6_5) ) ) ).

tff('Define:ctx:14',axiom,
    ! [X_9: $int] :
      ( mem0(X_9,g_s4_3)
    <=> ( $greatereq(X_9,0)
        & $lesseq(X_9,4294967295) ) ) ).

tff('Define:ctx:15',axiom,
    ! [X_10: $int] :
      ( mem0(X_10,g_s6_5)
    <=> ( $greatereq(X_10,0)
        & $lesseq(X_10,65535) ) ) ).

tff('Define:ctx:16',axiom,
    ! [X_11: $int] :
      ( mem0(X_11,g_s8_7)
    <=> ( $greatereq(X_11,0)
        & $lesseq(X_11,255) ) ) ).

tff('Define:ctx:17',axiom,
    mem0(g_s13_13,g_s4_3) ).

tff('Define:ctx:18',axiom,
    mem0(g_s14_14,g_s4_3) ).

tff('Define:ctx:19',axiom,
    mem0(g_s15_15,g_s4_3) ).

tff('Define:ctx:2',axiom,
    mem0(g_s5_6,g_s6_5) ).

tff('Define:ctx:20',axiom,
    ( $greater(g_s16_16,0)
    & $lesseq(g_s16_16,max_int) ) ).

tff('Define:ctx:21',axiom,
    ( $greater(g_s17_17,0)
    & $lesseq(g_s17_17,max_int) ) ).

tff('Define:ctx:22',axiom,
    ( $greater(g_s18_18,0)
    & $lesseq(g_s18_18,max_int) ) ).

tff('Define:ctx:23',axiom,
    $lesseq(g_s18_18,g_s17_17) ).

tff('Define:ctx:24',axiom,
    mem0(g_s19_19,g_s8_7) ).

tff('Define:ctx:25',axiom,
    mem0(g_s20_20,g_s8_7) ).

tff('Define:ctx:26',axiom,
    mem0(g_s21_21,g_s4_3) ).

tff('Define:ctx:27',axiom,
    mem0(g_s22_22,g_s4_3) ).

tff('Define:ctx:28',axiom,
    g_s20_20 = $sum(g_s19_19,g_s16_16) ).

tff('Define:ctx:29',axiom,
    g_s21_21 = $sum(g_s19_19,g_s17_17) ).

tff('Define:ctx:3',axiom,
    mem0(g_s7_8,g_s8_7) ).

tff('Define:ctx:30',axiom,
    g_s22_22 = $difference($sum(g_s19_19,g_s17_17),g_s18_18) ).

tff('Define:ctx:31',axiom,
    mem0(g_s23_23,g_s4_3) ).

tff('Define:ctx:32',axiom,
    mem0(g_s24_24,g_s4_3) ).

tff('Define:ctx:33',axiom,
    ( $greater(g_s25_25,0)
    & $lesseq(g_s25_25,max_int) ) ).

tff('Define:ctx:34',axiom,
    ( $greater(g_s26_26,0)
    & $lesseq(g_s26_26,max_int) ) ).

tff('Define:ctx:35',axiom,
    ( $greater(g_s27_27,0)
    & $lesseq(g_s27_27,max_int) ) ).

tff('Define:ctx:36',axiom,
    mem0(g_s28_28,g_s8_7) ).

tff('Define:ctx:37',axiom,
    mem0(g_s29_29,g_s8_7) ).

tff('Define:ctx:38',axiom,
    mem0(g_s30_30,g_s6_5) ).

tff('Define:ctx:39',axiom,
    mem0(g_s31_31,g_s8_7) ).

tff('Define:ctx:4',axiom,
    mem0(g_s9_9,g_s8_7) ).

tff('Define:ctx:40',axiom,
    g_s29_29 = $sum(g_s28_28,g_s25_25) ).

tff('Define:ctx:41',axiom,
    g_s30_30 = $sum(g_s28_28,g_s26_26) ).

tff('Define:ctx:42',axiom,
    g_s31_31 = $sum(g_s28_28,g_s27_27) ).

tff('Define:ctx:43',axiom,
    mem0(g_s32_32,g_s6_5) ).

tff('Define:ctx:44',axiom,
    mem0(g_s33_33,g_s6_5) ).

tff('Define:ctx:45',axiom,
    mem0(g_s34_34,g_s6_5) ).

tff('Define:ctx:46',axiom,
    ! [L_s35: $int] :
      ( mem0(L_s35,g_s4_3)
     => ! [X_12: $int] :
          ( mem3(L_s35,g_s34_34,X_12,g_s36_35)
         => $lesseq(X_12,1023) ) ) ).

tff('Define:ctx:47',axiom,
    mem0(g_s37_36,g_s6_5) ).

tff('Define:ctx:48',axiom,
    ( $greater(g_s38_37,0)
    & $lesseq(g_s38_37,max_int) ) ).

tff('Define:ctx:49',axiom,
    mem0(g_s39_38,g_s6_5) ).

tff('Define:ctx:5',axiom,
    mem0(g_s10_10,g_s8_7) ).

tff('Define:ctx:50',axiom,
    mem0(g_s40_39,g_s6_5) ).

tff('Define:ctx:51',axiom,
    g_s40_39 = $sum(g_s39_38,g_s38_37) ).

tff('Define:ctx:52',axiom,
    ( $greater(g_s41_40,0)
    & $lesseq(g_s41_40,max_int) ) ).

tff('Define:ctx:53',axiom,
    mem0(g_s42_41,g_s6_5) ).

tff('Define:ctx:54',axiom,
    mem0(g_s43_42,g_s6_5) ).

tff('Define:ctx:55',axiom,
    g_s43_42 = $sum(g_s42_41,g_s41_40) ).

tff('Define:ctx:56',axiom,
    mem0(g_s44_43,g_s4_3) ).

tff('Define:ctx:57',axiom,
    mem0(g_s45_44,g_s4_3) ).

tff('Define:ctx:58',axiom,
    mem0(g_s46_45,g_s4_3) ).

tff('Define:ctx:59',axiom,
    mem0(g_s47_46,g_s4_3) ).

tff('Define:ctx:6',axiom,
    g_s3_4 = 4294967295 ).

tff('Define:ctx:60',axiom,
    $lesseq(1,g_s47_46) ).

tff('Define:ctx:61',axiom,
    mem0(g_s48_47,g_s4_3) ).

tff('Define:ctx:62',axiom,
    mem0(g_s49_48,g_s4_3) ).

tff('Define:ctx:63',axiom,
    mem0(g_s50_49,g_s4_3) ).

tff('Define:ctx:64',axiom,
    ( $greater(g_s51_50,0)
    & $lesseq(g_s51_50,max_int) ) ).

tff('Define:ctx:65',axiom,
    g_s49_48 = $sum(g_s48_47,g_s51_50) ).

tff('Define:ctx:66',axiom,
    ( $greater(g_s52_51,0)
    & $lesseq(g_s52_51,max_int) ) ).

tff('Define:ctx:67',axiom,
    g_s50_49 = $sum(g_s48_47,g_s52_51) ).

tff('Define:ctx:68',axiom,
    mem0(g_s53_52,g_s4_3) ).

tff('Define:ctx:69',axiom,
    mem0(g_s54_53,g_s6_5) ).

tff('Define:ctx:7',axiom,
    g_s5_6 = 65535 ).

tff('Define:ctx:70',axiom,
    mem0(g_s55_54,g_s6_5) ).

tff('Define:ctx:71',axiom,
    ( $greater(g_s56_55,0)
    & $lesseq(g_s56_55,max_int) ) ).

tff('Define:ctx:72',axiom,
    g_s55_54 = $sum(g_s54_53,g_s56_55) ).

tff('Define:ctx:73',axiom,
    mem0(g_s57_56,g_s8_7) ).

tff('Define:ctx:74',axiom,
    $less(g_s57_56,g_s3_4) ).

tff('Define:ctx:75',axiom,
    ( $greater(g_s58_57,0)
    & $lesseq(g_s58_57,max_int) ) ).

tff('Define:ctx:76',axiom,
    g_s57_56 = $sum(g_s54_53,g_s58_57) ).

tff('Define:ctx:77',axiom,
    mem0(g_s59_58,g_s6_5) ).

tff('Define:ctx:78',axiom,
    mem0(g_s60_59,g_s4_3) ).

tff('Define:ctx:79',axiom,
    mem0(g_s61_60,g_s8_7) ).

tff('Define:ctx:8',axiom,
    g_s7_8 = 255 ).

tff('Define:ctx:80',axiom,
    mem0(g_s62_61,g_s8_7) ).

tff('Define:ctx:81',axiom,
    g_s62_61 = $difference(g_s61_60,1) ).

tff('Define:ctx:82',axiom,
    mem0(g_s63_62,g_s6_5) ).

tff('Define:ctx:83',axiom,
    mem0(g_s64_63,g_s6_5) ).

tff('Define:ctx:84',axiom,
    g_s64_63 = $product(g_s63_62,g_s61_60) ).

tff('Define:ctx:85',axiom,
    mem0(g_s65_64,g_s6_5) ).

tff('Define:ctx:86',axiom,
    mem0(g_s66_65,g_s8_7) ).

tff('Define:ctx:87',axiom,
    $lesseq(g_s63_62,g_s65_64) ).

tff('Define:ctx:88',axiom,
    $less(g_s64_63,g_s65_64) ).

tff('Define:ctx:89',axiom,
    g_s67_66 = $difference(g_s63_62,g_s66_65) ).

tff('Define:ctx:9',axiom,
    ( $greatereq(g_s9_9,0)
    & $lesseq(g_s9_9,g_s7_8) ) ).

tff('Define:ctx:90',axiom,
    g_s68_67 = $difference(g_s65_64,$product(g_s66_65,g_s61_60)) ).

tff('Define:ctx:91',axiom,
    mem0(g_s69_68,g_s4_3) ).

tff('Define:ctx:92',axiom,
    mem0(g_s70_69,g_s4_3) ).

tff('Define:ctx:93',axiom,
    mem0(g_s71_70,g_s4_3) ).

tff('Define:ctx:94',axiom,
    mem0(g_s72_71,g_s4_3) ).

tff('Define:ctx:95',axiom,
    mem0(g_s73_72,g_s4_3) ).

tff('Define:ctx:96',axiom,
    mem0(g_s74_73,g_s4_3) ).

tff('Define:ctx:97',axiom,
    mem0(g_s75_74,g_s4_3) ).

tff('Define:ctx:98',axiom,
    mem0(g_s76_75,g_s4_3) ).

tff('Define:ctx:99',axiom,
    mem0(g_s77_76,g_s4_3) ).

tff('Define:imext:0',axiom,
    ? [X_379: set_4] :
      ( ! [X_380: $int,X_381: $int] :
          ( mem4(X_381,X_380,X_379)
        <=> mem4(X_381,X_380,g_s109_1_103) )
      & ! [X_382: $int,X_383: $int,X_384: $int] :
          ( ( mem4(X_382,X_383,X_379)
            & mem4(X_382,X_384,X_379) )
         => ( X_383 = X_384 ) )
      & ! [X_385: $int] :
          ( mem0(X_385,g_s0_0)
        <=> ? [X_386: $int] : mem4(X_385,X_386,X_379) )
      & ! [X_387: $int] :
          ( ? [X_388: $int] : mem4(X_388,X_387,X_379)
         => $true ) ) ).

tff('Define:inv:0',axiom,
    ! [X_542: $int,X_543: $int] :
      ( mem4(X_543,X_542,g_s109_106)
    <=> mem4(X_543,X_542,g_s109_1_103) ) ).

tff('Define:inv:1',axiom,
    ? [X_544: set_4] :
      ( ! [X_545: $int,X_546: $int] :
          ( mem4(X_546,X_545,X_544)
        <=> mem4(X_546,X_545,g_s122_1_112) )
      & ! [X_547: $int,X_548: $int,X_549: $int] :
          ( ( mem4(X_547,X_548,X_544)
            & mem4(X_547,X_549,X_544) )
         => ( X_548 = X_549 ) )
      & ! [X_550: $int] :
          ( mem0(X_550,g_s0_0)
        <=> ? [X_551: $int] : mem4(X_550,X_551,X_544) )
      & ! [X_552: $int] :
          ( ? [X_553: $int] : mem4(X_553,X_552,X_544)
         => mem0(X_552,g_s8_7) ) ) ).

tff('Define:inv:2',axiom,
    ? [X_554: set_4] :
      ( ! [X_555: $int,X_556: $int] :
          ( mem4(X_556,X_555,X_554)
        <=> mem4(X_556,X_555,g_s123_1_113) )
      & ! [X_557: $int,X_558: $int,X_559: $int] :
          ( ( mem4(X_557,X_558,X_554)
            & mem4(X_557,X_559,X_554) )
         => ( X_558 = X_559 ) )
      & ! [X_560: $int] :
          ( mem0(X_560,g_s0_0)
        <=> ? [X_561: $int] : mem4(X_560,X_561,X_554) )
      & ! [X_562: $int] :
          ( ? [X_563: $int] : mem4(X_563,X_562,X_554)
         => mem0(X_562,g_s8_7) ) ) ).

tff('Define:inv:3',axiom,
    ? [X_564: set_4] :
      ( ! [X_565: $int,X_566: $int] :
          ( mem4(X_566,X_565,X_564)
        <=> mem4(X_566,X_565,g_s124_1_114) )
      & ! [X_567: $int,X_568: $int,X_569: $int] :
          ( ( mem4(X_567,X_568,X_564)
            & mem4(X_567,X_569,X_564) )
         => ( X_568 = X_569 ) )
      & ! [X_570: $int] :
          ( mem0(X_570,g_s0_0)
        <=> ? [X_571: $int] : mem4(X_570,X_571,X_564) )
      & ! [X_572: $int] :
          ( ? [X_573: $int] : mem4(X_573,X_572,X_564)
         => mem0(X_572,g_s4_3) ) ) ).

tff('Define:inv:4',axiom,
    ! [L_s121: $int] :
      ( mem0(L_s121,g_s0_0)
     => ! [X_574: $int] :
          ( ! [X_575: $o] :
              ( ( (X_575)
              <=> mem0(L_s121,g_s119_110) )
             => mem2((X_575),X_574,g_s12_12) )
         => mem4(L_s121,X_574,g_s122_1_112) ) ) ).

tff('Define:inv:5',axiom,
    ! [L_s121: $int] :
      ( mem0(L_s121,g_s0_0)
     => ! [X_576: $int] :
          ( ! [X_577: $o] :
              ( ( (X_577)
              <=> mem0(L_s121,g_s120_111) )
             => mem2((X_577),X_576,g_s12_12) )
         => mem4(L_s121,X_576,g_s123_1_113) ) ) ).

tff('Define:inv:6',axiom,
    ! [X_578: $int,X_579: $int] :
      ( mem4(X_579,X_578,g_s108_105)
    <=> mem4(X_579,X_578,g_s124_1_114) ) ).

tff('Define:seext:0',axiom,
    ( ! [X_389: $int,X_390: $o] :
        ( mem2((X_390),X_389,g_s12_12)
       => ( $true
          & mem0(X_389,g_s8_7) ) )
    & ! [X_391: $o,X_392: $int,X_393: $int] :
        ( ( mem2((X_391),X_392,g_s12_12)
          & mem2((X_391),X_393,g_s12_12) )
       => ( X_392 = X_393 ) ) ) ).

tff('Define:seext:1',axiom,
    ( ! [X_394: $int,X_395: $o] :
        ( mem2((X_395),X_394,g_s12_12)
       => ( $true
          & mem0(X_394,g_s6_5) ) )
    & ! [X_396: $o,X_397: $int,X_398: $int] :
        ( ( mem2((X_396),X_397,g_s12_12)
          & mem2((X_396),X_398,g_s12_12) )
       => ( X_397 = X_398 ) ) ) ).

tff('Define:seext:2',axiom,
    ( ! [X_399: $int,X_400: $o] :
        ( mem2((X_400),X_399,g_s12_12)
       => ( $true
          & mem0(X_399,g_s4_3) ) )
    & ! [X_401: $o,X_402: $int,X_403: $int] :
        ( ( mem2((X_401),X_402,g_s12_12)
          & mem2((X_401),X_403,g_s12_12) )
       => ( X_402 = X_403 ) ) ) ).

%Global hypotheses
%----Local hypotheses
tff('Local_Hyp:0',hypothesis,
    mem0(g_s128_115,g_s0_0) ).

tff('Local_Hyp:1',hypothesis,
    mem0(g_s129_116,g_s4_3) ).

tff('Local_Hyp:2',hypothesis,
    mem0(g_s130_117,g_s4_3) ).

tff('Local_Hyp:3',hypothesis,
    mem0(g_s131_118,g_s4_3) ).

tff('Local_Hyp:4',hypothesis,
    mem0(g_s132_119,g_s8_7) ).

tff('Local_Hyp:5',hypothesis,
    mem0(g_s133_120,g_s4_3) ).

tff('Local_Hyp:6',hypothesis,
    mem0(g_s134_121,g_s4_3) ).

tff('Local_Hyp:7',hypothesis,
    g_s132_119 = g_s9_9 ).

tff('Local_Hyp:8',hypothesis,
    ~ ! [X_580: $int] :
        ( mem3(g_s129_116,g_s34_34,X_580,g_s36_35)
       => mem4(X_580,g_s130_117,g_s80_79) ) ).

tff('Local_Hyp:9',hypothesis,
    ! [X_585: $int] :
      ( ( X_585 = 0 )
     => mem0(X_585,g_s4_3) ) ).

tff('Local_Hyp:10',hypothesis,
    ! [X_586: $int] :
      ( ( X_586 = 11 )
     => mem0(X_586,g_s4_3) ) ).

tff('Local_Hyp:11',hypothesis,
    ! [X_587: $int] :
      ( ! [X_588: $int] :
          ( mem3(g_s129_116,g_s34_34,X_588,g_s36_35)
         => mem4(X_588,X_587,g_s80_79) )
     => mem0(X_587,g_s4_3) ) ).

tff('Local_Hyp:12',hypothesis,
    ! [X_590: $int] :
      ( ( X_590 = 12 )
     => mem0(X_590,g_s4_3) ) ).

%----Goal
tff('Goal',conjecture,
    ! [X_591: $int] :
      ( ( X_591 = 13 )
     => mem0(X_591,g_s4_3) ) ).

%------------------------------------------------------------------------------
