%------------------------------------------------------------------------------
% File     : LCL942_2 : TPTP v9.2.1. Released v8.2.0.
% Domain   : General Algebra
% Problem  : Goedel translation of ALG017+1
% Version  : [QMLTP] axioms.
% English  : 

% Refs     : [Goe69] Goedel (1969), An Interpretation of the Intuitionistic
%          : [RO12]  Raths & Otten (2012), The QMLTP Problem Library for Fi
% Source   : [QMLTP]
% Names    : GAL017+1 [QMLTP]

% Status   : Theorem
% Rating   : 0.00 v8.2.0
% Syntax   : Number of formulae    :   33 (   3 unt;  12 typ;   0 def)
%            Number of atoms       :  728 (   0 equ)
%            Maximal formula atoms :  144 (  34 avg)
%            Number of connectives :  769 (  62   ~;  69   |; 199   &)
%                                         (   0 <=>; 439  =>;   0  <=;   0 <~>)
%            Maximal formula depth :   66 (  16 avg)
%            Maximal term depth    :    3 (   1 avg)
%            Number of types       :    3 (   1 usr)
%            Number of type conns  :   10 (   5   >;   5   *;   0   +;   0  <<)
%            Number of predicates  :    3 (   3 usr;   0 prp; 2-3 aty)
%            Number of functors    :    8 (   8 usr;   6 con; 0-2 aty)
%            Number of variables   :  423 (; 422   !;   1   ?; 423   :)
% SPC      : TF0_THM_NEQ_NAR

% Comments : Generated by embedproblem, version 1.7.14, rigid constant,
%            modal_system_M, TFF embedding.
%------------------------------------------------------------------------------
tff('$ki_world_type',type,
    '$ki_world': $tType ).

tff('$ki_local_world_decl',type,
    '$ki_local_world': '$ki_world' ).

tff('$ki_accessible_decl',type,
    '$ki_accessible': ( '$ki_world' * '$ki_world' ) > $o ).

tff(mrel_reflexive,axiom,
    ! [W: '$ki_world'] : '$ki_accessible'(W,W) ).

tff(unit_decl,type,
    unit: $i ).

tff(e0_decl,type,
    e0: $i ).

tff(e1_decl,type,
    e1: $i ).

tff(e2_decl,type,
    e2: $i ).

tff(e3_decl,type,
    e3: $i ).

tff(qmltpeq_decl,type,
    qmltpeq: ( '$ki_world' * $i * $i ) > $o ).

tff(inv_decl,type,
    inv: $i > $i ).

tff(op_decl,type,
    op: ( $i * $i ) > $i ).

tff('$ki_exists_in_world_$i_decl',type,
    '$ki_exists_in_world_$i': ( '$ki_world' * $i ) > $o ).

tff('$ki_exists_in_world_$i_const',axiom,
    ! [W: '$ki_world',X: $i] : '$ki_exists_in_world_$i'(W,X) ).

tff('$ki_exists_in_world_$i_nonempty',axiom,
    ! [W: '$ki_world'] :
    ? [X: $i] : '$ki_exists_in_world_$i'(W,X) ).

tff(reflexivity,axiom,
    ! [W: '$ki_world'] :
      ( '$ki_accessible'('$ki_local_world',W)
     => ! [X: $i] :
          ( '$ki_exists_in_world_$i'(W,X)
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,X,X) ) ) ) ).

tff(symmetry,axiom,
    ! [W: '$ki_world'] :
      ( '$ki_accessible'('$ki_local_world',W)
     => ! [X: $i] :
          ( '$ki_exists_in_world_$i'(W,X)
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => ! [Y: $i] :
                  ( '$ki_exists_in_world_$i'(W0,Y)
                 => ! [W1: '$ki_world'] :
                      ( '$ki_accessible'(W0,W1)
                     => ( ! [W2: '$ki_world'] :
                            ( '$ki_accessible'(W1,W2)
                           => qmltpeq(W2,X,Y) )
                       => ! [W2: '$ki_world'] :
                            ( '$ki_accessible'(W1,W2)
                           => qmltpeq(W2,Y,X) ) ) ) ) ) ) ) ).

tff(transitivity,axiom,
    ! [W: '$ki_world'] :
      ( '$ki_accessible'('$ki_local_world',W)
     => ! [X: $i] :
          ( '$ki_exists_in_world_$i'(W,X)
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => ! [Y: $i] :
                  ( '$ki_exists_in_world_$i'(W0,Y)
                 => ! [W1: '$ki_world'] :
                      ( '$ki_accessible'(W0,W1)
                     => ! [Z: $i] :
                          ( '$ki_exists_in_world_$i'(W1,Z)
                         => ! [W2: '$ki_world'] :
                              ( '$ki_accessible'(W1,W2)
                             => ( ( ! [W3: '$ki_world'] :
                                      ( '$ki_accessible'(W2,W3)
                                     => qmltpeq(W3,X,Y) )
                                  & ! [W3: '$ki_world'] :
                                      ( '$ki_accessible'(W2,W3)
                                     => qmltpeq(W3,Y,Z) ) )
                               => ! [W3: '$ki_world'] :
                                    ( '$ki_accessible'(W2,W3)
                                   => qmltpeq(W3,X,Z) ) ) ) ) ) ) ) ) ) ).

tff(inv_substitution_1,axiom,
    ! [W: '$ki_world'] :
      ( '$ki_accessible'('$ki_local_world',W)
     => ! [A: $i] :
          ( '$ki_exists_in_world_$i'(W,A)
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => ! [B: $i] :
                  ( '$ki_exists_in_world_$i'(W0,B)
                 => ! [W1: '$ki_world'] :
                      ( '$ki_accessible'(W0,W1)
                     => ( ! [W2: '$ki_world'] :
                            ( '$ki_accessible'(W1,W2)
                           => qmltpeq(W2,A,B) )
                       => ! [W2: '$ki_world'] :
                            ( '$ki_accessible'(W1,W2)
                           => qmltpeq(W2,inv(A),inv(B)) ) ) ) ) ) ) ) ).

tff(op_substitution_1,axiom,
    ! [W: '$ki_world'] :
      ( '$ki_accessible'('$ki_local_world',W)
     => ! [A: $i] :
          ( '$ki_exists_in_world_$i'(W,A)
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => ! [B: $i] :
                  ( '$ki_exists_in_world_$i'(W0,B)
                 => ! [W1: '$ki_world'] :
                      ( '$ki_accessible'(W0,W1)
                     => ! [C: $i] :
                          ( '$ki_exists_in_world_$i'(W1,C)
                         => ! [W2: '$ki_world'] :
                              ( '$ki_accessible'(W1,W2)
                             => ( ! [W3: '$ki_world'] :
                                    ( '$ki_accessible'(W2,W3)
                                   => qmltpeq(W3,A,B) )
                               => ! [W3: '$ki_world'] :
                                    ( '$ki_accessible'(W2,W3)
                                   => qmltpeq(W3,op(A,C),op(B,C)) ) ) ) ) ) ) ) ) ) ).

tff(op_substitution_2,axiom,
    ! [W: '$ki_world'] :
      ( '$ki_accessible'('$ki_local_world',W)
     => ! [A: $i] :
          ( '$ki_exists_in_world_$i'(W,A)
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => ! [B: $i] :
                  ( '$ki_exists_in_world_$i'(W0,B)
                 => ! [W1: '$ki_world'] :
                      ( '$ki_accessible'(W0,W1)
                     => ! [C: $i] :
                          ( '$ki_exists_in_world_$i'(W1,C)
                         => ! [W2: '$ki_world'] :
                              ( '$ki_accessible'(W1,W2)
                             => ( ! [W3: '$ki_world'] :
                                    ( '$ki_accessible'(W2,W3)
                                   => qmltpeq(W3,A,B) )
                               => ! [W3: '$ki_world'] :
                                    ( '$ki_accessible'(W2,W3)
                                   => qmltpeq(W3,op(C,A),op(C,B)) ) ) ) ) ) ) ) ) ) ).

tff(ax1,axiom,
    ( ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e0,e0),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e0,e0),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e0,e0),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e0,e0),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e0,e1),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e0,e1),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e0,e1),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e0,e1),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e0,e2),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e0,e2),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e0,e2),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e0,e2),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e0,e3),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e0,e3),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e0,e3),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e0,e3),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e1,e0),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e1,e0),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e1,e0),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e1,e0),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e1,e1),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e1,e1),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e1,e1),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e1,e1),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e1,e2),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e1,e2),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e1,e2),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e1,e2),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e1,e3),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e1,e3),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e1,e3),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e1,e3),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e2,e0),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e2,e0),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e2,e0),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e2,e0),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e2,e1),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e2,e1),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e2,e1),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e2,e1),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e2,e2),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e2,e2),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e2,e2),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e2,e2),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e2,e3),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e2,e3),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e2,e3),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e2,e3),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e3,e0),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e3,e0),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e3,e0),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e3,e0),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e3,e1),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e3,e1),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e3,e1),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e3,e1),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e3,e2),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e3,e2),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e3,e2),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e3,e2),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e3,e3),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e3,e3),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e3,e3),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,op(e3,e3),e3) ) ) ) ).

tff(ax2,axiom,
    ( ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e0,e0),e0),op(e0,op(e0,e0))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e0,e0),e1),op(e0,op(e0,e1))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e0,e0),e2),op(e0,op(e0,e2))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e0,e0),e3),op(e0,op(e0,e3))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e0,e1),e0),op(e0,op(e1,e0))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e0,e1),e1),op(e0,op(e1,e1))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e0,e1),e2),op(e0,op(e1,e2))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e0,e1),e3),op(e0,op(e1,e3))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e0,e2),e0),op(e0,op(e2,e0))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e0,e2),e1),op(e0,op(e2,e1))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e0,e2),e2),op(e0,op(e2,e2))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e0,e2),e3),op(e0,op(e2,e3))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e0,e3),e0),op(e0,op(e3,e0))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e0,e3),e1),op(e0,op(e3,e1))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e0,e3),e2),op(e0,op(e3,e2))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e0,e3),e3),op(e0,op(e3,e3))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e1,e0),e0),op(e1,op(e0,e0))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e1,e0),e1),op(e1,op(e0,e1))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e1,e0),e2),op(e1,op(e0,e2))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e1,e0),e3),op(e1,op(e0,e3))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e1,e1),e0),op(e1,op(e1,e0))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e1,e1),e1),op(e1,op(e1,e1))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e1,e1),e2),op(e1,op(e1,e2))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e1,e1),e3),op(e1,op(e1,e3))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e1,e2),e0),op(e1,op(e2,e0))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e1,e2),e1),op(e1,op(e2,e1))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e1,e2),e2),op(e1,op(e2,e2))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e1,e2),e3),op(e1,op(e2,e3))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e1,e3),e0),op(e1,op(e3,e0))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e1,e3),e1),op(e1,op(e3,e1))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e1,e3),e2),op(e1,op(e3,e2))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e1,e3),e3),op(e1,op(e3,e3))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e2,e0),e0),op(e2,op(e0,e0))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e2,e0),e1),op(e2,op(e0,e1))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e2,e0),e2),op(e2,op(e0,e2))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e2,e0),e3),op(e2,op(e0,e3))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e2,e1),e0),op(e2,op(e1,e0))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e2,e1),e1),op(e2,op(e1,e1))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e2,e1),e2),op(e2,op(e1,e2))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e2,e1),e3),op(e2,op(e1,e3))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e2,e2),e0),op(e2,op(e2,e0))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e2,e2),e1),op(e2,op(e2,e1))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e2,e2),e2),op(e2,op(e2,e2))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e2,e2),e3),op(e2,op(e2,e3))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e2,e3),e0),op(e2,op(e3,e0))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e2,e3),e1),op(e2,op(e3,e1))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e2,e3),e2),op(e2,op(e3,e2))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e2,e3),e3),op(e2,op(e3,e3))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e3,e0),e0),op(e3,op(e0,e0))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e3,e0),e1),op(e3,op(e0,e1))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e3,e0),e2),op(e3,op(e0,e2))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e3,e0),e3),op(e3,op(e0,e3))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e3,e1),e0),op(e3,op(e1,e0))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e3,e1),e1),op(e3,op(e1,e1))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e3,e1),e2),op(e3,op(e1,e2))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e3,e1),e3),op(e3,op(e1,e3))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e3,e2),e0),op(e3,op(e2,e0))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e3,e2),e1),op(e3,op(e2,e1))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e3,e2),e2),op(e3,op(e2,e2))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e3,e2),e3),op(e3,op(e2,e3))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e3,e3),e0),op(e3,op(e3,e0))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e3,e3),e1),op(e3,op(e3,e1))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e3,e3),e2),op(e3,op(e3,e2))) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(op(e3,e3),e3),op(e3,op(e3,e3))) ) ) ).

tff(ax3,axiom,
    ( ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(unit,e0),e0) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(e0,unit),e0) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(unit,e1),e1) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(e1,unit),e1) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(unit,e2),e2) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(e2,unit),e2) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(unit,e3),e3) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(e3,unit),e3) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,unit,e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,unit,e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,unit,e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,unit,e3) ) ) ) ).

tff(ax4,axiom,
    ( ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(e0,inv(e0)),unit) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(inv(e0),e0),unit) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(e1,inv(e1)),unit) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(inv(e1),e1),unit) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(e2,inv(e2)),unit) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(inv(e2),e2),unit) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(e3,inv(e3)),unit) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,op(inv(e3),e3),unit) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,inv(e0),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,inv(e0),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,inv(e0),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,inv(e0),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,inv(e1),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,inv(e1),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,inv(e1),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,inv(e1),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,inv(e2),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,inv(e2),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,inv(e2),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,inv(e2),e3) ) )
    & ( ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,inv(e3),e0) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,inv(e3),e1) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,inv(e3),e2) )
      | ! [W: '$ki_world'] :
          ( '$ki_accessible'('$ki_local_world',W)
         => qmltpeq(W,inv(e3),e3) ) ) ) ).

tff(ax5,axiom,
    ! [W: '$ki_world'] :
      ( '$ki_accessible'('$ki_local_world',W)
     => qmltpeq(W,inv(unit),unit) ) ).

tff(ax6,axiom,
    ( ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,inv(inv(e0)),e0) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,inv(inv(e1)),e1) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,inv(inv(e2)),e2) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,inv(inv(e3)),e3) ) ) ).

tff(ax7,axiom,
    ( ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ( ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e0),e0) )
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e0),e0) ) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ( ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e0),e1) )
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e1),e0) ) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ( ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e0),e2) )
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e2),e0) ) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ( ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e0),e3) )
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e3),e0) ) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ( ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e1),e0) )
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e0),e1) ) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ( ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e1),e1) )
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e1),e1) ) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ( ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e1),e2) )
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e2),e1) ) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ( ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e1),e3) )
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e3),e1) ) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ( ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e2),e0) )
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e0),e2) ) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ( ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e2),e1) )
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e1),e2) ) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ( ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e2),e2) )
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e2),e2) ) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ( ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e2),e3) )
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e3),e2) ) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ( ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e3),e0) )
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e0),e3) ) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ( ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e3),e1) )
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e1),e3) ) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ( ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e3),e2) )
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e2),e3) ) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ( ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e3),e3) )
         => ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e3),e3) ) ) ) ) ).

tff(ax8,axiom,
    ( ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e0),inv(e1)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e0),inv(e2)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e0),inv(e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e1),inv(e2)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e1),inv(e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,inv(e2),inv(e3)) ) ) ) ).

tff(ax9,axiom,
    ( ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e0),op(e1,e0)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e0),op(e2,e0)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e0),op(e3,e0)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e1,e0),op(e2,e0)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e1,e0),op(e3,e0)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e2,e0),op(e3,e0)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e1),op(e1,e1)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e1),op(e2,e1)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e1),op(e3,e1)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e1,e1),op(e2,e1)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e1,e1),op(e3,e1)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e2,e1),op(e3,e1)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e2),op(e1,e2)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e2),op(e2,e2)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e2),op(e3,e2)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e1,e2),op(e2,e2)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e1,e2),op(e3,e2)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e2,e2),op(e3,e2)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e3),op(e1,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e3),op(e2,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e3),op(e3,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e1,e3),op(e2,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e1,e3),op(e3,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e2,e3),op(e3,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e0),op(e0,e1)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e0),op(e0,e2)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e0),op(e0,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e1),op(e0,e2)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e1),op(e0,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e0,e2),op(e0,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e1,e0),op(e1,e1)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e1,e0),op(e1,e2)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e1,e0),op(e1,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e1,e1),op(e1,e2)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e1,e1),op(e1,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e1,e2),op(e1,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e2,e0),op(e2,e1)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e2,e0),op(e2,e2)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e2,e0),op(e2,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e2,e1),op(e2,e2)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e2,e1),op(e2,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e2,e2),op(e2,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e3,e0),op(e3,e1)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e3,e0),op(e3,e2)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e3,e0),op(e3,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e3,e1),op(e3,e2)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e3,e1),op(e3,e3)) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,op(e3,e2),op(e3,e3)) ) ) ) ).

tff(ax10,axiom,
    ( ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,e0,e1) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,e0,e2) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,e0,e3) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,e1,e2) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,e1,e3) ) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => ~ ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => qmltpeq(W0,e2,e3) ) ) ) ).

tff(ax11,axiom,
    ( ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,e0,op(e3,e3)) )
    & ! [W: '$ki_world'] :
        ( '$ki_accessible'('$ki_local_world',W)
       => qmltpeq(W,e1,op(e2,e3)) ) ) ).

tff(verify,conjecture,
    ! [W: '$ki_world'] :
      ( '$ki_accessible'('$ki_local_world',W)
     => ~ ( ( ( ! [W0: '$ki_world'] :
                  ( '$ki_accessible'(W,W0)
                 => qmltpeq(W0,op(e0,e0),e0) )
              & ! [W0: '$ki_world'] :
                  ( '$ki_accessible'(W,W0)
                 => qmltpeq(W0,op(e1,e1),e0) )
              & ! [W0: '$ki_world'] :
                  ( '$ki_accessible'(W,W0)
                 => qmltpeq(W0,op(e2,e2),e0) )
              & ! [W0: '$ki_world'] :
                  ( '$ki_accessible'(W,W0)
                 => qmltpeq(W0,op(e3,e3),e0) ) )
            | ( ! [W0: '$ki_world'] :
                  ( '$ki_accessible'(W,W0)
                 => qmltpeq(W0,op(e0,e0),e1) )
              & ! [W0: '$ki_world'] :
                  ( '$ki_accessible'(W,W0)
                 => qmltpeq(W0,op(e1,e1),e1) )
              & ! [W0: '$ki_world'] :
                  ( '$ki_accessible'(W,W0)
                 => qmltpeq(W0,op(e2,e2),e1) )
              & ! [W0: '$ki_world'] :
                  ( '$ki_accessible'(W,W0)
                 => qmltpeq(W0,op(e3,e3),e1) ) )
            | ( ! [W0: '$ki_world'] :
                  ( '$ki_accessible'(W,W0)
                 => qmltpeq(W0,op(e0,e0),e2) )
              & ! [W0: '$ki_world'] :
                  ( '$ki_accessible'(W,W0)
                 => qmltpeq(W0,op(e1,e1),e2) )
              & ! [W0: '$ki_world'] :
                  ( '$ki_accessible'(W,W0)
                 => qmltpeq(W0,op(e2,e2),e2) )
              & ! [W0: '$ki_world'] :
                  ( '$ki_accessible'(W,W0)
                 => qmltpeq(W0,op(e3,e3),e2) ) )
            | ( ! [W0: '$ki_world'] :
                  ( '$ki_accessible'(W,W0)
                 => qmltpeq(W0,op(e0,e0),e3) )
              & ! [W0: '$ki_world'] :
                  ( '$ki_accessible'(W,W0)
                 => qmltpeq(W0,op(e1,e1),e3) )
              & ! [W0: '$ki_world'] :
                  ( '$ki_accessible'(W,W0)
                 => qmltpeq(W0,op(e2,e2),e3) )
              & ! [W0: '$ki_world'] :
                  ( '$ki_accessible'(W,W0)
                 => qmltpeq(W0,op(e3,e3),e3) ) ) )
          & ! [W0: '$ki_world'] :
              ( '$ki_accessible'(W,W0)
             => ~ ( ( ! [W1: '$ki_world'] :
                        ( '$ki_accessible'(W0,W1)
                       => qmltpeq(W1,op(e0,e0),e0) )
                    & ! [W1: '$ki_world'] :
                        ( '$ki_accessible'(W0,W1)
                       => qmltpeq(W1,op(e1,e1),e0) )
                    & ! [W1: '$ki_world'] :
                        ( '$ki_accessible'(W0,W1)
                       => qmltpeq(W1,op(e2,e2),e0) )
                    & ! [W1: '$ki_world'] :
                        ( '$ki_accessible'(W0,W1)
                       => qmltpeq(W1,op(e3,e3),e0) ) )
                  | ( ! [W1: '$ki_world'] :
                        ( '$ki_accessible'(W0,W1)
                       => qmltpeq(W1,op(e0,e0),e1) )
                    & ! [W1: '$ki_world'] :
                        ( '$ki_accessible'(W0,W1)
                       => qmltpeq(W1,op(e1,e1),e1) )
                    & ! [W1: '$ki_world'] :
                        ( '$ki_accessible'(W0,W1)
                       => qmltpeq(W1,op(e2,e2),e1) )
                    & ! [W1: '$ki_world'] :
                        ( '$ki_accessible'(W0,W1)
                       => qmltpeq(W1,op(e3,e3),e1) ) )
                  | ( ! [W1: '$ki_world'] :
                        ( '$ki_accessible'(W0,W1)
                       => qmltpeq(W1,op(e0,e0),e2) )
                    & ! [W1: '$ki_world'] :
                        ( '$ki_accessible'(W0,W1)
                       => qmltpeq(W1,op(e1,e1),e2) )
                    & ! [W1: '$ki_world'] :
                        ( '$ki_accessible'(W0,W1)
                       => qmltpeq(W1,op(e2,e2),e2) )
                    & ! [W1: '$ki_world'] :
                        ( '$ki_accessible'(W0,W1)
                       => qmltpeq(W1,op(e3,e3),e2) ) )
                  | ( ! [W1: '$ki_world'] :
                        ( '$ki_accessible'(W0,W1)
                       => qmltpeq(W1,op(e0,e0),e3) )
                    & ! [W1: '$ki_world'] :
                        ( '$ki_accessible'(W0,W1)
                       => qmltpeq(W1,op(e1,e1),e3) )
                    & ! [W1: '$ki_world'] :
                        ( '$ki_accessible'(W0,W1)
                       => qmltpeq(W1,op(e2,e2),e3) )
                    & ! [W1: '$ki_world'] :
                        ( '$ki_accessible'(W0,W1)
                       => qmltpeq(W1,op(e3,e3),e3) ) ) ) ) ) ) ).

%------------------------------------------------------------------------------
