%------------------------------------------------------------------------------
% File     : SYO651-1 : TPTP v9.2.1. Released v7.3.0.
% Domain   : Syntactic
% Problem  : GSM_1_2_4
% Version  : Especial.
% English  :

% Refs     : [EH+16] Ebner et al. (2016), System Description: GAPT 2.0
%          : [Cer18] Cerna (2018), Email to Geoff Sutcliffe
% Source   : [Cer18]
% Names    : GSM_1_2_4 [Cer18]

% Status   : Unsatisfiable
% Rating   : 0.15 v9.1.0, 0.18 v9.0.0, 0.17 v8.2.0, 0.14 v8.1.0, 0.00 v7.4.0, 0.17 v7.3.0
% Syntax   : Number of clauses     :   75 (   2 unt;  62 nHn;  74 RR)
%            Number of literals    : 1276 (   0 equ;1114 neg)
%            Maximal clause size   :   26 (  17 avg)
%            Maximal term depth    :    6 (   2 avg)
%            Number of predicates  :    3 (   3 usr;   0 prp; 2-2 aty)
%            Number of functors    :    5 (   5 usr;   2 con; 0-1 aty)
%            Number of variables   :  202 (   1 sgn)
% SPC      : CNF_UNS_RFO_NEQ_NHN

% Comments : Created using the GAPT system - https://github.com/gapt/gapt/blob/
%            master/examples/schema/GradedStrictMonotoneSequenceSchema.scala
%------------------------------------------------------------------------------
cnf(clause_2802,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_7))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | 'E'(f(B_6),f(suc(suc(suc(B_6))))) ) ).

cnf(clause_2744,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | 'E'(f(B_7),f(suc(suc(suc(B_7))))) ) ).

cnf(clause_1772,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | iLEQ(suc(A_1),suc(A_1)) ) ).

cnf(clause_613,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_6))))))
    | ~ 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_7),f(suc(suc(B_7)))) ) ).

cnf(clause_1532,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_7))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | 'E'(f(B_6),f(suc(suc(B_6)))) ) ).

cnf(clause_3823,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_6),f(suc(suc(B_6))))
    | 'E'(f(B_7),f(suc(B_7))) ) ).

cnf(clause_733,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | 'E'(f(B_6),f(suc(suc(B_6))))
    | 'E'(f(B_7),f(suc(suc(suc(B_7))))) ) ).

cnf(clause_1536,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | 'E'(f(B_7),f(suc(suc(B_7)))) ) ).

cnf(clause_1318,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_7))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_6),f(suc(suc(suc(B_6))))) ) ).

cnf(clause_3677,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(B_7),f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_7))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_6),f(suc(suc(suc(B_6))))) ) ).

cnf(clause_2650,axiom,
    ( ~ 'LE'(f(suc(B_5)),s('0'))
    | 'E'('0',f(suc(B_5)))
    | 'LE'(f(B_5),'0') ) ).

cnf(clause_2891,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_7))))))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | 'E'(f(B_6),f(suc(B_6))) ) ).

cnf(clause_1098,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_6))))))
    | ~ 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(B_7),f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_7))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(A_1)))) ) ).

cnf(clause_3530,axiom,
    'LE'(f(A),s('0')) ).

cnf(clause_3578,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | 'E'(f(B_7),f(suc(suc(suc(B_7))))) ) ).

cnf(clause_187,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_6))))))
    | ~ 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | 'E'(f(B_7),f(suc(suc(B_7)))) ) ).

cnf(clause_492,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | 'E'(f(B_7),f(suc(B_7))) ) ).

cnf(clause_2573,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_6))))))
    | ~ 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_7),f(suc(B_7))) ) ).

cnf(clause_3275,axiom,
    ( ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_6),f(suc(B_6)))
    | 'E'(f(B_7),f(suc(suc(B_7)))) ) ).

cnf(clause_3274,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | 'E'(f(B_7),f(suc(suc(suc(B_7))))) ) ).

cnf(clause_1875,axiom,
    ( ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_6),f(suc(B_6)))
    | 'E'(f(B_7),f(suc(B_7))) ) ).

cnf(clause_627,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(B_6),f(suc(suc(B_6))))
    | 'E'(f(B_7),f(suc(suc(B_7)))) ) ).

cnf(clause_2277,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_6),f(suc(suc(B_6))))
    | 'E'(f(B_7),f(suc(suc(suc(B_7))))) ) ).

cnf(clause_3412,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | 'E'(f(B_7),f(suc(B_7))) ) ).

cnf(clause_2612,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_6),f(suc(suc(B_6))))
    | 'E'(f(B_7),f(suc(suc(B_7)))) ) ).

cnf(clause_2529,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(B_6),f(suc(suc(B_6))))
    | 'E'(f(B_7),f(suc(suc(suc(B_7))))) ) ).

cnf(clause_935,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(B_6),f(suc(B_6)))
    | 'E'(f(B_7),f(suc(suc(B_7)))) ) ).

cnf(clause_255,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_6))))))
    | ~ 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | 'E'(f(B_7),f(suc(suc(suc(B_7))))) ) ).

cnf(clause_2887,axiom,
    ( ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(A_1))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_6),f(suc(B_6)))
    | 'E'(f(B_7),f(suc(B_7))) ) ).

cnf(clause_1563,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_6))))))
    | ~ 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(B_7),f(suc(suc(suc(B_7))))) ) ).

cnf(clause_3718,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_6),f(suc(suc(B_6))))
    | 'E'(f(B_7),f(suc(suc(suc(B_7))))) ) ).

cnf(clause_3339,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | 'E'(f(B_7),f(suc(suc(B_7)))) ) ).

cnf(clause_2312,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | 'E'(f(B_6),f(suc(suc(B_6))))
    | 'E'(f(B_7),f(suc(suc(B_7)))) ) ).

cnf(clause_426,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_6))))))
    | ~ 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(B_7),f(suc(B_7))) ) ).

cnf(clause_3575,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_7))))))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(B_6),f(suc(suc(B_6)))) ) ).

cnf(clause_3112,axiom,
    ( ~ 'LE'(f(suc(suc(B_5))),s('0'))
    | 'E'('0',f(suc(suc(B_5))))
    | 'LE'(f(B_5),'0') ) ).

cnf(clause_2518,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | 'E'(f(B_7),f(suc(suc(suc(B_7))))) ) ).

cnf(clause_1816,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | 'E'(f(B_6),f(suc(B_6)))
    | 'E'(f(B_7),f(suc(B_7))) ) ).

cnf(clause_1829,axiom,
    ~ 'LE'(f(z),'0') ).

cnf(clause_1564,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_6))))))
    | ~ 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_7),f(suc(B_7))) ) ).

cnf(clause_408,axiom,
    ( ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(B_7),f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_7))))))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_6),f(suc(B_6))) ) ).

cnf(clause_1901,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_6))))))
    | ~ 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(B_7),f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_7))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1))))) ) ).

cnf(clause_3408,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | 'E'(f(B_6),f(suc(suc(B_6))))
    | 'E'(f(B_7),f(suc(B_7))) ) ).

cnf(clause_619,axiom,
    ( ~ 'LE'(f(suc(suc(suc(suc(B_5))))),s('0'))
    | 'E'('0',f(suc(suc(suc(suc(B_5))))))
    | 'LE'(f(B_5),'0') ) ).

cnf(clause_403,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_7))))))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(B_6),f(suc(suc(suc(B_6))))) ) ).

cnf(clause_3827,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | iLEQ(suc(A_1),suc(A_1)) ) ).

cnf(clause_960,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_6))))))
    | ~ 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(B_7),f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_7))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(A_1))) ) ).

cnf(clause_752,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_6))))))
    | ~ 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_7),f(suc(suc(suc(B_7))))) ) ).

cnf(clause_3337,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_7))))))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(B_6),f(suc(B_6))) ) ).

cnf(clause_55,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_6))))))
    | ~ 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | 'E'(f(B_7),f(suc(B_7))) ) ).

cnf(clause_1587,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(B_6),f(suc(suc(B_6))))
    | 'E'(f(B_7),f(suc(B_7))) ) ).

cnf(clause_896,axiom,
    ( ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_6),f(suc(B_6)))
    | 'E'(f(B_7),f(suc(suc(suc(B_7))))) ) ).

cnf(clause_930,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | 'E'(f(B_7),f(suc(B_7))) ) ).

cnf(clause_2899,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(B_6),f(suc(B_6)))
    | 'E'(f(B_7),f(suc(B_7))) ) ).

cnf(clause_3669,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_6))))))
    | ~ 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(B_7),f(suc(suc(B_7)))) ) ).

cnf(clause_2721,axiom,
    ( ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_7))))))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_6),f(suc(B_6))) ) ).

cnf(clause_2386,axiom,
    ( ~ 'LE'(f(B_5),s('0'))
    | 'E'('0',f(B_5))
    | 'LE'(f(B_5),'0') ) ).

cnf(clause_1550,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(A_1))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_6),f(suc(suc(B_6))))
    | 'E'(f(B_7),f(suc(B_7))) ) ).

cnf(clause_3129,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_6))))))
    | ~ 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_7),f(suc(suc(B_7)))) ) ).

cnf(clause_1229,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | 'E'(f(B_6),f(suc(B_6)))
    | 'E'(f(B_7),f(suc(suc(suc(B_7))))) ) ).

cnf(clause_3293,axiom,
    ( ~ 'LE'(f(suc(suc(suc(B_5)))),s('0'))
    | 'E'('0',f(suc(suc(suc(B_5)))))
    | 'LE'(f(B_5),'0') ) ).

cnf(clause_249,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | 'E'(f(B_7),f(suc(suc(B_7)))) ) ).

cnf(clause_698,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | 'E'(f(B_7),f(suc(suc(B_7)))) ) ).

cnf(clause_3360,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_6))))))
    | ~ 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | ~ 'E'(f(B_7),f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_7))))))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6))) ) ).

cnf(clause_1427,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | 'E'(f(B_7),f(suc(B_7))) ) ).

cnf(clause_2015,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_6)))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_6))))))
    | ~ 'E'(f(B_6),f(suc(suc(suc(B_6)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'(f(B_6),f(suc(suc(B_6))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_7),f(suc(suc(suc(B_7))))) ) ).

cnf(clause_2993,axiom,
    ( ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(A_1))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | iLEQ(suc(A_1),suc(A_1)) ) ).

cnf(clause_2195,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(B_7),f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_7))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_6),f(suc(suc(B_6)))) ) ).

cnf(clause_1366,axiom,
    ( ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_6),f(suc(B_6)))
    | 'E'(f(B_7),f(suc(suc(B_7)))) ) ).

cnf(clause_2665,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | 'E'(f(B_6),f(suc(B_6)))
    | 'E'(f(B_7),f(suc(suc(B_7)))) ) ).

cnf(clause_1375,axiom,
    ( ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_6),f(suc(B_6)))
    | 'E'(f(B_7),f(suc(suc(suc(B_7))))) ) ).

cnf(clause_3155,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'(f(A_1),f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(A_1))))))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(B_6),f(suc(B_6)))
    | 'E'(f(B_7),f(suc(suc(suc(B_7))))) ) ).

cnf(clause_2054,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'(f(B_7),f(suc(suc(B_7))))
    | ~ 'E'('0',f(suc(suc(suc(B_7)))))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'('0',f(suc(suc(suc(suc(B_7))))))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_6),f(suc(suc(B_6)))) ) ).

cnf(clause_636,axiom,
    ( ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(A_1)))
    | 'E'(f(A_1),f(suc(A_1)))
    | iLEQ(suc(A_1),suc(A_1)) ) ).

cnf(clause_3679,axiom,
    ( ~ 'E'('0',f(suc(suc(B_6))))
    | ~ iLEQ(suc(A_1),suc(B_6))
    | ~ 'E'('0',f(suc(B_7)))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(B_7),f(suc(B_7)))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(suc(B_7))))
    | ~ iLEQ(suc(B_6),suc(B_7))
    | ~ 'E'('0',f(B_6))
    | ~ 'E'('0',f(B_7))
    | ~ 'E'(f(B_6),f(suc(B_6)))
    | ~ 'E'('0',f(suc(B_6)))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_6),f(suc(suc(B_6))))
    | 'E'(f(B_7),f(suc(suc(B_7)))) ) ).

%------------------------------------------------------------------------------
