%------------------------------------------------------------------------------
% File     : SYO653-1 : TPTP v9.2.1. Released v7.3.0.
% Domain   : Syntactic
% Problem  : GSM_1_3_3
% Version  : Especial.
% English  :

% Refs     : [EH+16] Ebner et al. (2016), System Description: GAPT 2.0
%          : [Cer18] Cerna (2018), Email to Geoff Sutcliffe
% Source   : [Cer18]
% Names    : GSM_1_3_3 [Cer18]

% Status   : Unsatisfiable
% Rating   : 0.15 v9.1.0, 0.18 v9.0.0, 0.17 v8.2.0, 0.14 v8.1.0, 0.00 v7.4.0, 0.33 v7.3.0
% Syntax   : Number of clauses     :   90 (   2 unt;  78 nHn;  89 RR)
%            Number of literals    : 1786 (   0 equ;1556 neg)
%            Maximal clause size   :   27 (  19 avg)
%            Maximal term depth    :    5 (   2 avg)
%            Number of predicates  :    3 (   3 usr;   0 prp; 2-2 aty)
%            Number of functors    :    5 (   5 usr;   2 con; 0-1 aty)
%            Number of variables   :  332 (   1 sgn)
% SPC      : CNF_UNS_RFO_NEQ_NHN

% Comments : Created using the GAPT system - https://github.com/gapt/gapt/blob/
%            master/examples/schema/GradedStrictMonotoneSequenceSchema.scala
%------------------------------------------------------------------------------
cnf(clause_2175,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(suc(B_12)))) ) ).

cnf(clause_482,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_50,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_1508,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_12),f(suc(suc(B_12)))) ) ).

cnf(clause_1036,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_286,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(suc(B_12)))) ) ).

cnf(clause_2102,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_102,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_704,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_971,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(B_12))) ) ).

cnf(clause_1371,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_1048,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_2031,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_419,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_554,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_1556,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_54,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_316,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_2134,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_1719,axiom,
    ( ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'('0',f(A_1))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | iLEQ(suc(A_1),suc(A_1)) ) ).

cnf(clause_1057,axiom,
    ~ 'LE'(f(z),'0') ).

cnf(clause_1596,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_383,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_498,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(B_12))) ) ).

cnf(clause_1550,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_114,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(suc(B_11)))) ) ).

cnf(clause_244,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_306,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_872,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_2036,axiom,
    'LE'(f(A),s('0')) ).

cnf(clause_1387,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_1143,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_912,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(B_11))) ) ).

cnf(clause_961,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(suc(B_11)))) ) ).

cnf(clause_903,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_683,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_227,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_12),f(suc(suc(B_12)))) ) ).

cnf(clause_268,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(B_12))) ) ).

cnf(clause_541,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_1773,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(suc(B_12)))) ) ).

cnf(clause_51,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_2198,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_68,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(B_12))) ) ).

cnf(clause_765,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_1091,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_1221,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_12),f(suc(suc(B_12)))) ) ).

cnf(clause_1893,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_12),f(suc(B_12))) ) ).

cnf(clause_1277,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_1976,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(suc(B_12)))) ) ).

cnf(clause_1983,axiom,
    ( ~ 'LE'(f(suc(B_10)),s('0'))
    | 'E'('0',f(suc(B_10)))
    | 'LE'(f(B_10),'0') ) ).

cnf(clause_714,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_1480,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(B_11))) ) ).

cnf(clause_2157,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_148,axiom,
    ( ~ 'LE'(f(B_10),s('0'))
    | 'E'('0',f(B_10))
    | 'LE'(f(B_10),'0') ) ).

cnf(clause_142,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_1836,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12)) ) ).

cnf(clause_1953,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_1615,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(suc(B_12)))) ) ).

cnf(clause_1528,axiom,
    ( ~ 'LE'(f(suc(suc(suc(B_10)))),s('0'))
    | 'E'('0',f(suc(suc(suc(B_10)))))
    | 'LE'(f(B_10),'0') ) ).

cnf(clause_295,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_263,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_12),f(suc(B_12))) ) ).

cnf(clause_433,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1)))) ) ).

cnf(clause_107,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_1791,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_94,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1))) ) ).

cnf(clause_1568,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(B_11))) ) ).

cnf(clause_1883,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_1384,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_2160,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_2101,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_12),f(suc(B_12))) ) ).

cnf(clause_1148,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(suc(B_11)))) ) ).

cnf(clause_1315,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_1934,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_931,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_38,axiom,
    ( ~ 'LE'(f(suc(suc(B_10))),s('0'))
    | 'E'('0',f(suc(suc(B_10))))
    | 'LE'(f(B_10),'0') ) ).

cnf(clause_1337,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_391,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(suc(B_12)))) ) ).

cnf(clause_1597,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_1404,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_972,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | iLEQ(suc(A_1),suc(A_1)) ) ).

cnf(clause_878,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_20,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_1039,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ 'E'('0',f(suc(suc(suc(B_11)))))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'(f(B_11),f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_354,axiom,
    ( ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(suc(A_1)))
    | 'E'(f(A_1),f(suc(A_1)))
    | iLEQ(suc(A_1),suc(A_1)) ) ).

cnf(clause_246,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_877,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_12),f(suc(suc(B_12))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_12)))))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_1801,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(B_12)))
    | 'E'(f(B_13),f(suc(B_13))) ) ).

cnf(clause_942,axiom,
    ( ~ 'E'('0',f(suc(suc(suc(A_1)))))
    | ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(A_1),f(suc(suc(A_1))))
    | ~ 'E'(f(B_12),f(suc(B_12)))
    | ~ 'E'('0',f(suc(suc(B_12))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(suc(B_12))))
    | 'E'(f(B_13),f(suc(suc(B_13)))) ) ).

cnf(clause_380,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(suc(suc(A_1))))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(A_1),f(suc(A_1)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(suc(A_1))))
    | 'E'(f(B_11),f(suc(B_11)))
    | 'E'(f(B_12),f(suc(B_12))) ) ).

cnf(clause_1161,axiom,
    ( ~ 'E'('0',f(suc(B_11)))
    | ~ iLEQ(suc(B_12),suc(B_13))
    | ~ 'E'('0',f(suc(suc(B_11))))
    | ~ 'E'('0',f(suc(A_1)))
    | ~ 'E'('0',f(B_11))
    | ~ 'E'('0',f(A_1))
    | ~ 'E'('0',f(B_13))
    | ~ 'E'('0',f(suc(B_12)))
    | ~ 'E'(f(B_13),f(suc(suc(B_13))))
    | ~ 'E'(f(B_11),f(suc(B_11)))
    | ~ iLEQ(suc(A_1),suc(B_11))
    | ~ 'E'('0',f(suc(B_13)))
    | ~ 'E'('0',f(B_12))
    | ~ 'E'('0',f(suc(suc(suc(B_13)))))
    | ~ 'E'('0',f(suc(suc(B_13))))
    | ~ 'E'(f(B_13),f(suc(B_13)))
    | ~ iLEQ(suc(B_11),suc(B_12))
    | 'E'(f(A_1),f(suc(A_1)))
    | 'E'(f(B_11),f(suc(suc(B_11))))
    | 'E'(f(B_12),f(suc(B_12))) ) ).

%------------------------------------------------------------------------------
